var region = "Gesundbrunnen";

var gymjson = {
"gyms": [
{"value":"1892 Historisches Gebäude","token":"historisches haus","map":"https://goo.gl/maps/LJthotdr7b72"},
{"value":"AEG Beamtentor","map":"https://goo.gl/maps/pCd3BJgke8B2"},
{"value":"Amtsgericht Wedding","ex":true,"map":"https://goo.gl/maps/q79rW3P5iz82"},
{"value":"Bahnhof Humboldthain","token":"s-bahnhof","map":"https://goo.gl/maps/NoMxjQmX8Yz"},
{"value":"Bahnsteig S-Bahnhof Gesundbrunnen","map":"https://goo.gl/maps/P6fLg6nSaKM2"},
{"value":"Balance on the Globe","tg":"Balance On The Globe","map":"https://goo.gl/maps/bM2QWrCkDhq"},
{"value":"Berliner Mauer S Wollankstraße","token":"s-bahnhof","map":"https://goo.gl/maps/7ggyACh3c7y"},
{"value":"Birkenmural","map":"https://goo.gl/maps/LUjPLZgELHR2"},
{"value":"Bornholmer Straße Border Crossing","map":"https://goo.gl/maps/borFEx1Zp3D2"},
{"value":"Bösebrücke Bornholmer Straße","map":"https://goo.gl/maps/Fkb2uqJf8kJ2"},
{"value":"Brunnen DRK","tg":"Brunnen","map":"https://goo.gl/maps/WqegcLtthPx"},
{"value":"Brunnenstraße","token":"u-bahnhof voltastraße","map":"https://goo.gl/maps/QEN9FksYAUR2"},
{"value":"Bunker Humboldthain","map":"https://goo.gl/maps/Q5xj3TTdQfR2"},
{"value":"Caritas Berlin","map":"https://goo.gl/maps/hETMiMPwxyo"},
{"value":"Drei-Säulen-Brunnen","map":"https://goo.gl/maps/BD6HAd3WwAC2"},
{"value":"Eingangstor St. Elisabeth","token":"friedhof kirchhof cemetery graveyard","map":"https://goo.gl/maps/6WQqtbYTLFD2"},
{"value":"Ente","ex":true,"token":"🦆","map":"https://goo.gl/maps/nXUzN45onnB2"},
{"value":"Ernst Reuter Büste","map":"https://goo.gl/maps/c3bK2hVWqy32"},
{"value":"Ev. Stephanus Kirche","map":"https://goo.gl/maps/t3zqccxjfS5YzZsT7"},
{"value":"Gedenkstein Opfer der Berliner Mauer","map":"https://goo.gl/maps/vKCJtW7CXjm"},
{"value":"Gewachsen auf Beton Mural","token":"u-bahnhof pankstraße","map":"https://goo.gl/maps/8MVUihQXCQ82"},
{"value":"Haus Graffiti","map":"https://goo.gl/maps/RgpNp4xwBZS2"},
{"value":"Hausmalerei","map":"https://goo.gl/maps/wJXuVvpzvTv"},
{"value":"Hauswächter","map":"https://goo.gl/maps/Yv9g8aRw9S72"},
{"value":"Hippo Fountain","ex":true,"map":"https://goo.gl/maps/zRQmhYSnYTG2"},
{"value":"Humboldtpark","map":"https://goo.gl/maps/L6gci4KrmRM2"},
{"value":"Jungfräulich Maria St.","tg":"jungfräulich Maria St.","token":"sankt petrus bellermannstraße","map":"https://goo.gl/maps/4qMqQB4rPXG2"},
{"value":"Jux und Tollerei","map":"https://goo.gl/maps/vLZcbgbGXrD2"},
{"value":"Kamel","ex":true,"token":"🐫 🐪","map":"https://goo.gl/maps/xCWVtJhqw1r"},
{"value":"Kulturverein Christiana","map":"https://goo.gl/maps/Mks22S8syUn"},
{"value":"Mother Statue","map":"https://goo.gl/maps/obrXpaCe8Kp"},
{"value":"Portal zur Kaiser Wilhelm und Augusta Stiftung","tg":"Portal zur Kaiser Wilhelm Und Augusta Stiftung","map":"https://goo.gl/maps/Z132sxwCnHE2"},
{"value":"Rosengarten am Humboldthain","tg":"Rosengarten am Humboldhain","map":"https://goo.gl/maps/uuFsiJBmDp72"},
{"value":"S-Bahnhof Bornholmer Straße","map":"https://goo.gl/maps/fTpjjxxPXbK2"},
{"value":"Shadow People","map":"https://goo.gl/maps/PzqU2mtenL42"},
{"value":"Spinnennetz Spielplatz","token":"🕸️","map":"https://goo.gl/maps/vKtfoyDAsoS2"},
{"value":"Springbrunnen am Rathaus","tg":"Springbrunnen Am Rathaus","map":"https://goo.gl/maps/j5WL5s81k2K2"},
{"value":"St. Sebastian-Kirche","ex":true,"map":"https://goo.gl/maps/za2Fq6XPC5t"},
{"value":"Stolpersteine Georg und Rudolf Juliusburger","tg":"Stolpersteine Georg Und Rudolf Juliusburger","token":"jüdisches krankenhaus jewish hospital","map":"https://goo.gl/maps/kPsKT4sGpPK2"},
{"value":"Stone Snake","token":"🐍","map":"https://goo.gl/maps/1vVp7mPAtzH2"},
{"value":"Swinemünder Brücke","map":"https://goo.gl/maps/hH2WCCHeLwK2"},
{"value":"The Real Old Mechanical Door","map":"https://goo.gl/maps/WvKP2eCWdu12"},
{"value":"U-Bahnhof Osloer Straße","tg":"U-Bahnhof Osloer Strasse","map":"https://goo.gl/maps/67rcURgu1Y82"},
{"value":"Vergessene Brücke","map":"https://goo.gl/maps/NTR2AcNt6pp"},
{"value":"Wyndham Garden Entrance Relief","token":"hotel","map":"https://goo.gl/maps/o2XreJkiJTx"},
{"value":"Zwillingsstatue","ex":true,"map":"https://goo.gl/maps/q1rctADEE8q"}
]};

var boqlink = "https://www.bookofquests.de/#14/1490031.01/6900393.52/0/f=";