var region = "Marzahn";

var gymjson = {
"gyms": [
{"value":"Ahrensfelde Bahnhof","map":"https://goo.gl/maps/6BLe343fgsK3GCou5"},
{"value":"Alles nur Fassade","tg":"Alles Nur Fassade","map":"https://goo.gl/maps/no9mhgAMRqrvCEmE9"},
{"value":"Anna Landsberger","map":"https://goo.gl/maps/qUgwn3vNBwe7CuQp6"},
{"value":"Bahnsteig Raoul-Wallenberg-Str.","token":"s-bahnhof","map":"https://goo.gl/maps/Zkx8JCJXfHTv34Y9A"},
{"value":"Bemalte Stromkästen","map":"https://goo.gl/maps/y8MsdpES7xX5gU528"},
{"value":"Berliner Bär Knorr Bremse","map":"https://goo.gl/maps/6nuwrUdo4QqQW8gQ8"},
{"value":"Boxer Mural","map":"https://goo.gl/maps/qvf8vFXgyQMroxEq5"},
{"value":"Boxkreuz am SC Eintracht Berlin","map":"https://goo.gl/maps/ArYPQbCKrhKuxDRH7"},
{"value":"Brunnen am Ahrensfelder Berg","map":"https://goo.gl/maps/TkUkUuF9MhSviKft5"},
{"value":"Brunnen am Eastgate","map":"https://goo.gl/maps/FLd1u6DsVcJSNh1x9"},
{"value":"Brunnen Pumpe","map":"https://goo.gl/maps/ssFnzuuzXAGEXvWf9"},
{"value":"Bus Station Graffiti","map":"https://goo.gl/maps/urcSgKBXs6ts5PNw9"},
{"value":"BVG Kundenzentrum","map":"https://goo.gl/maps/FLnHbDo54FWLVuEeA"},
{"value":"CityArt - Stromhäuschen","map":"https://goo.gl/maps/X8nLUJ4YTLeCtbq27"},
{"value":"Clara Zetkin","map":"https://goo.gl/maps/oMvz4Xb6TeXDKmT68"},
{"value":"Colour Your Life","map":"https://goo.gl/maps/PhHRZktSKMfs8ePz6"},
{"value":"Countdown 2010","map":"https://goo.gl/maps/umr5EYygwYHmshvx9"},
{"value":"Denkmal für die Erbauer Marzahns","map":"https://goo.gl/maps/5Xaqw9Sn8baYX7ASA"},
{"value":"Der Lachende Verteiler","map":"https://goo.gl/maps/gAdBmKFCMrQdWs5V6"},
{"value":"Die 3 Bleistifte von Johann Strauß","map":"https://goo.gl/maps/QBNbtQ5cH6c28ESFA"},
{"value":"Drache im Gras","map":"https://goo.gl/maps/eWja5JyhidSe1Xqo7"},
{"value":"Econopark","map":"https://goo.gl/maps/6VQU4B8HvPsseN896"},
{"value":"Eingang Gärten der Welt","map":"https://goo.gl/maps/FdKExoXRbQk9HuQeA"},
{"value":'Einkaufszentrum "Eastgate"',"map":"https://goo.gl/maps/5tgiKAVAmMpGnZcw8"},
{"value":"Fassade","map":"https://goo.gl/maps/hP7tyvcr9mWfpuqS8"},
{"value":"Firefighter Berlin","map":"https://goo.gl/maps/6aeFT1wKqhjQZPbf8"},
{"value":"Flower Tower","map":"https://goo.gl/maps/T3bZpdXzSDL2Hn1b9"},
{"value":"Freiheit","map":"https://goo.gl/maps/xQx4xXA4mdFvRbXV6"},
{"value":"Friedrichsfelde Ost S-Bahnhof","map":"https://goo.gl/maps/ikByn7Dxhw2S82eGA"},
{"value":"Früher Vogel","map":"https://goo.gl/maps/r3PjCRQKdNtvGbMZ6"},
{"value":"Gärten der Welt, Hintereingang","map":"https://goo.gl/maps/WEvcb8fSPojvbcDR8"},
{"value":"Gangster Kamel","map":"https://goo.gl/maps/ehjQU1SSy9hWiXd59"},
{"value":"Gasflaschen-Kunst","map":"https://goo.gl/maps/JbYUBLuCRsPdUnPM6"},
{"value":"Gate","map":"https://goo.gl/maps/6Y5uoC5UjWqv4FU18"},
{"value":"Gedenkstein","map":"https://goo.gl/maps/PxSmfnSJgJAsfPiB6"},
{"value":"Gesichter-Statue","map":"https://goo.gl/maps/JtCjuZmsZuKgUbsE8"},
{"value":"Grafitimonster","map":"https://goo.gl/maps/2DneEAdF1XD8titH7"},
{"value":"Grafitti an der Druckerhöhungsstation","map":"https://goo.gl/maps/ydCFy8o2kEQFY3187"},
{"value":"Greek Warrior","map":"https://goo.gl/maps/2ZapQAHjuUN35vrW8"},
{"value":"Green Guy","map":"https://goo.gl/maps/tEhqqxAB2nx1dP8q8"},
{"value":"Griechische Statue","map":"https://goo.gl/maps/hGipR9rTzmND2cDN7"},
{"value":"Häuptling am Spielplatz","map":"https://goo.gl/maps/QwQzTXf5TTH1354y8"},
{"value":"Hallo Moderne Skulptur","map":"https://goo.gl/maps/Wv6zdyZbkj9uGyM96"},
{"value":"High Voltage Man","map":"https://goo.gl/maps/J43qX2WGr7UGvxvH9"},
{"value":"Hirsch","map":"https://goo.gl/maps/FJwFemXJMMUbmpVg7"},
{"value":"Hochzeitsgarten","hidden":true,"map":"https://goo.gl/maps/fcdUXYjCTWtrP8pH7"},
{"value":"Hochzeitsplattform","map":"https://goo.gl/maps/BGnrywMziQD68mJMA"},
{"value":"Interkultureller Garten Marzahn e.V.","map":"https://goo.gl/maps/xJnWKAukw93hA3EN8"},
{"value":"Iron Man","map":"https://goo.gl/maps/cdEyM5Be4kYgRgCV7"},
{"value":"Jazz Graffiti","map":"https://goo.gl/maps/YT9ABt5ftxfQsd4GA"},
{"value":"Jugendclub Impuls","map":"https://goo.gl/maps/xkhRojE9cBZLgEKw5"},
{"value":"Kegel","map":"https://goo.gl/maps/vX5z28EDCFJCLCxo8"},
{"value":"Kienberg Monument","map":"https://goo.gl/maps/seDoTb9acrDXtUmt8"},
{"value":"Kiez","map":"https://goo.gl/maps/5heTHWp4S6DgVaq48"},
{"value":"Kinder - Grundschule an der Geissenweide","map":"https://goo.gl/maps/bwTGduSMuLUUdoJm8"},
{"value":"Kirche St.Konrad von Parzheim","map":"https://goo.gl/maps/hvQxh2uybdwbmwBZ7"},
{"value":"Kleiner Mann","map":"https://goo.gl/maps/UHuSQj62mkKRMK9B7"},
{"value":"Kletterburg","map":"https://goo.gl/maps/iC87o71FC8k6ydsB7"},
{"value":"Kletterhaus","map":"https://goo.gl/maps/kWNq2akkC8saJ7Ye8"},
{"value":"Klettern am Boschpoler Platz","map":"https://goo.gl/maps/T3X2PGDMXDKab7WQ8"},
{"value":"Knospenbrunnen Marzahn","map":"https://goo.gl/maps/nK4Qh4wMatCLEUb4A"},
{"value":"Königspaar","map":"https://goo.gl/maps/FaYyFXiFvs34jumMA"},
{"value":"Krokodile","map":"https://goo.gl/maps/R88n8tMNz15LV467A"},
{"value":"Löwenkopf","map":"https://goo.gl/maps/cPHF4WxXYrRJhxNY6"},
{"value":"Lustiger E Kasten","map":"https://goo.gl/maps/F62CYDoyEqbeBKpW9"},
{"value":"Märkische Allee - Brücke","map":"https://goo.gl/maps/mc49LTJGtvcCT8z96"},
{"value":"Malerei an der Kita Marzähnchen","map":"https://goo.gl/maps/9W1fHWCmBDKx89Zm8"},
{"value":"Mann auf Pfahl","map":"https://goo.gl/maps/M36pCoohozqhLSMk7"},
{"value":"Mann mit Vogel","map":"https://goo.gl/maps/cUCi5kX4Yjqs965m8"},
{"value":"Mehrower Party","map":"https://goo.gl/maps/bySEdmbpbPRyLg5Y7"},
{"value":"Moderne Kunst","map":"https://goo.gl/maps/Nkwvfbwv4mUpc4kv6"},
{"value":"Mural Container","map":"https://goo.gl/maps/8THGxDjRQxS6M2Na6"},
{"value":"Opfer des Bombenterrors WK II","tg":"Opfer Des Bombenterrors wk II","map":"https://goo.gl/maps/1kDQJJ7KcwWeN8kx8"},
{"value":"Orgelpumpe","map":"https://goo.gl/maps/G9osP8GWDd9gua3k8"},
{"value":"Orpheus und Euridike 1984","map":"https://goo.gl/maps/jMDLqQ5fWT68pJ24A"},
{"value":"Orthodoxe Kirche","map":"https://goo.gl/maps/eZ8fUfbg59F7zxWh7"},
{"value":"Paar","map":"https://goo.gl/maps/xRNYdFhtmLrdGBTa8"},
{"value":"Pärchen","map":"https://goo.gl/maps/bW4u21kxcN3wpKvi8"},
{"value":"Pat & Patachon","map":"https://goo.gl/maps/TffshDUWNzpxmrub8"},
{"value":"Plastischer Körper","map":"https://goo.gl/maps/Zwgk1PUJRrDXZK5P9"},
{"value":"Pyramide Marzahn","map":"https://goo.gl/maps/wvhAp9WWJHLiXEYD8"},
{"value":"Quietsche-Ente","map":"https://goo.gl/maps/CzEfm7BEAdjfsJTC7"},
{"value":"Rathaus Ahrensfelde","map":"https://goo.gl/maps/qhKtKsmMxsD2SFmh7"},
{"value":"Red Sculpture","map":"https://goo.gl/maps/Tvv3RiyjsGpxxfeWA"},
{"value":"Reifenkröhnung","map":"https://goo.gl/maps/H6qgUQonsv1Kw6kd6"},
{"value":"Richtungskreuz","map":"https://goo.gl/maps/CUz1zhZpEpKweHYf7"},
{"value":"Rotes Spinnennetz","map":"https://goo.gl/maps/gybJccmS1rLRW6NYA"},
{"value":"Rudolf #2","map":"https://goo.gl/maps/TZieBbNeb2fx77fc8"},
{"value":"S-Bahnhof Berlin-Marzahn","map":"https://goo.gl/maps/eyccn25gNUopPTCM7"},
{"value":"S-Bahnhof Biesdorf","map":"https://goo.gl/maps/bcBtdiahSRJkC2PW7"},
{"value":"S-Bahnhof Mehrower Allee","map":"https://goo.gl/maps/G5oWKiBLstzv3eVk9"},
{"value":"S-Bahnhof Springpfuhl","map":"https://goo.gl/maps/yVqHJiCbdXUyxRn79"},
{"value":"Schwalbenkasten","map":"https://goo.gl/maps/G2TP127sSBG7EcW49"},
{"value":"Schwarzwurzel","map":"https://goo.gl/maps/rFL1XSLqQCUiNM8G9"},
{"value":"Segel am Bärenstein","map":"https://goo.gl/maps/aEAto5KyKstRFeSF7"},
{"value":"Sitzgruppe am Gehrensee","map":"https://goo.gl/maps/AvgA2gwM6CWXMEFN8"},
{"value":"Skulptur am Barnim Platz","map":"https://goo.gl/maps/skWirZN2gfMn7gvd7"},
{"value":"Skulptur Familie im Gruenen","tg":"Skulptur Familie Im Gruenen","map":"https://goo.gl/maps/6xixdB24W8ypD9XF9"},
{"value":"Skyline Kasten","map":"https://goo.gl/maps/HrUXgNEkv6WaB9FD7"},
{"value":"Sommer in Marzahn","tg":"Sommer In Marzahn","map":"https://goo.gl/maps/4QFnX6jrbqqGQYKQ6"},
{"value":"Sonne der Kita Sonne","map":"https://goo.gl/maps/iq2tQrKYZEpwsx4H7"},
{"value":"Sonne Mond und Sterne","tg":"Sonne Mond Und Sterne","map":"https://goo.gl/maps/DNnEevxGGcpfQ2jV9"},
{"value":"Sowjetisches Ehrenmal Ahrensfelde","map":"https://goo.gl/maps/v7KpppUCh6mAAPcp8"},
{"value":"Spielplatz Amanlisweg","map":"https://goo.gl/maps/BSBu5ne5WYLLerAF9"},
{"value":"Spielplatz - Havemannstr 🎠","map":"https://goo.gl/maps/ZvxiP4Q6HfRjRg2a9"},
{"value":"Sport Figures","map":"https://goo.gl/maps/Pv5PK67n4hJPfXza7"},
{"value":"Springbrunnenkunst","map":"https://goo.gl/maps/eDHQ3cUn7fWZMSL88"},
{"value":"Springpfuhl Brunnen","map":"https://goo.gl/maps/Mx6HEJEXNSnQZ3dP7"},
{"value":"Statue am Ahrensfelder Berg","map":"https://goo.gl/maps/T7hLxuZcfSdS1VRQ7"},
{"value":"Statue der Unwissenheit 2","map":"https://goo.gl/maps/fi1q7TB2wTzj8DnZA"},
{"value":"Steinrudel","map":"https://goo.gl/maps/bz2HrASgWYB21qCq8"},
{"value":"Steinskulptur","map":"https://goo.gl/maps/jhvk799iWp9mdJgn9"},
{"value":"Taucher","map":"https://goo.gl/maps/im1RQC2SSE6481Jx7"},
{"value":"The Minion","map":"https://goo.gl/maps/8QT1hLNrFr2CE3jT6"},
{"value":"Tims Buddy Bear","map":"https://goo.gl/maps/YNNXHnG5eUqwUEqNA"},
{"value":"Tramhaltestelle Beilsteiner Str.","map":"https://goo.gl/maps/XmSuiT8DC47x5AHF8"},
{"value":"Tram Station Allee D. Kosmonauten/Rhinstr.","map":"https://goo.gl/maps/wQbrhEaD3p7KQAXB6"},
{"value":"U-Boot","map":"https://goo.gl/maps/6ZurAbSNDLKWgaMn8"},
{"value":"Uhr am Blumberger Damm","map":"https://goo.gl/maps/9ZLdToSL9nfPbupB8"},
{"value":"Versteinerte Marienkäfer","map":"https://goo.gl/maps/qzSoUPHkeuFupwRu5"},
{"value":"Wasser Spielplatz","map":"https://goo.gl/maps/a51opWovYhKtpJdC8"},
{"value":"Wo Wohnen Wenig Kostet","map":"https://goo.gl/maps/P85AZEfcgD1HmD7J9"},
{"value":"Wuhletalwächter","map":"https://goo.gl/maps/V1qAyRyjdKCUy1QL9"},
{"value":"WW2 Befreiung Marzahn","map":"https://goo.gl/maps/hQwAdiKVbfemeokWA"},
{"value":"Великие подвиги Ваши бессмертны","token":"russisch kyrillisch sowjetisches ehrenmal parkfriedhof velikiye podvigi vashi bessmertny","map":"https://goo.gl/maps/jB5GL2qXSoFJvskH7"}
]};

var boqlink = "https://www.bookofquests.de/#13/1509651.48/6898631.34/0/f=";