var pokemon = [
{"dex":1,"name":"Bisasam","en":"Bulbasaur","getshiny":true},
{"dex":2,"name":"Bisaknosp","en":"Ivysaur","evolved":true},
{"dex":3,"name":"Bisaflor","en":"Venusaur","evolved":true,"getshiny":true},
{"dex":4,"name":"Glumanda","en":"Charmander","getshiny":true},
{"dex":5,"name":"Glutexo","en":"Charmeleon","evolved":true},
{"dex":6,"name":"Glurak","en":"Charizard","evolved":true,"getshiny":true},
{"dex":7,"name":"Schiggy","en":"Squirtle","getshiny":true},
{"dex":8,"name":"Schillok","en":"Wartortle","evolved":true},
{"dex":9,"name":"Turtok","en":"Blastoise","evolved":true,"getshiny":true},
{"dex":10,"name":"Raupy","en":"Caterpie","getshiny":true},
{"dex":11,"name":"Safcon","en":"Metapod","evolved":true},
{"dex":12,"name":"Smettbo","en":"Butterfree","evolved":true,"getshiny":true},
{"dex":13,"name":"Hornliu","en":"Weedle","getshiny":true},
{"dex":14,"name":"Kokuna","en":"Kakuna","evolved":true},
{"dex":15,"name":"Bibor","en":"Beedrill","evolved":true,"getshiny":true},
{"dex":16,"name":"Taubsi","en":"Pidgey","getshiny":true},
{"dex":17,"name":"Tauboga","en":"Pidgeotto","evolved":true},
{"dex":18,"name":"Tauboss","en":"Pidgeot","evolved":true,"getshiny":true},
{"dex":19,"name":"Rattfratz","en":"Rattata","getshiny":true},
{"dex":"19A","name":"Alola-Rattfratz","en":"Alolan Rattata","alolan":true,"getshiny":true},
{"dex":20,"name":"Rattikarl","en":"Raticate","evolved":true},
{"dex":"20A","name":"Alola-Rattikarl","en":"Alolan Raticate","alolan":true,"evolved":true},
{"dex":21,"name":"Habitak","en":"Spearow","getshiny":true},
{"dex":22,"name":"Ibitak","en":"Fearow","evolved":true},
{"dex":23,"name":"Rettan","en":"Ekans","getshiny":true},
{"dex":24,"name":"Arbok","evolved":true},
{"dex":25,"name":"Pikachu","getshiny":true},
{"dex":26,"name":"Raichu","evolved":true},
{"dex":"26A","name":"Alola-Raichu","en":"Alolan Raichu","alolan":true,"evolved":true,"getshiny":true},
{"dex":27,"name":"Sandan","en":"Sandshrew","getshiny":true},
{"dex":"27A","name":"Alola-Sandan","en":"Alolan Sandshrew","alolan":true,"getshiny":true},
{"dex":28,"name":"Sandamer","en":"Sandslash","evolved":true},
{"dex":"28A","name":"Alola-Sandamer","en":"Alolan Sandslash","alolan":true,"evolved":true},
{"dex":29,"name":"Nidoran♀","getshiny":true},
{"dex":30,"name":"Nidorina","evolved":true},
{"dex":31,"name":"Nidoqueen","evolved":true},
{"dex":32,"name":"Nidoran♂","getshiny":true},
{"dex":33,"name":"Nidorino","evolved":true},
{"dex":34,"name":"Nidoking","evolved":true},
{"dex":35,"name":"Piepi","en":"Clefairy","getshiny":true},
{"dex":36,"name":"Pixi","en":"Clefable","evolved":true},
{"dex":37,"name":"Vulpix","getshiny":true},
{"dex":"37A","name":"Alola-Vulpix","en":"Alolan Vulpix","alolan":true,"getshiny":true},
{"dex":38,"name":"Vulnona","en":"Ninetales","evolved":true},
{"dex":"38A","name":"Alola-Vulnona","en":"Alolan Ninetales","alolan":true,"evolved":true},
{"dex":39,"name":"Pummeluff","en":"Jigglypuff","getshiny":true},
{"dex":40,"name":"Knuddeluff","en":"Wigglytuff","evolved":true},
{"dex":41,"name":"Zubat","getshiny":true},
{"dex":42,"name":"Golbat","evolved":true,"getshiny":true},
{"dex":43,"name":"Myrapla","en":"Oddish","getshiny":true},
{"dex":44,"name":"Duflor","en":"Gloom","evolved":true,"getshiny":true},
{"dex":45,"name":"Giflor","en":"Vileplume","evolved":true},
{"dex":46,"name":"Paras","getshiny":true},
{"dex":47,"name":"Parasek","en":"Parasect","evolved":true},
{"dex":48,"name":"Bluzuk","en":"Venonat","getshiny":true},
{"dex":49,"name":"Omot","en":"Venomoth","evolved":true},
{"dex":50,"name":"Digda","en":"Diglett","getshiny":true},
{"dex":"50A","name":"Alola-Digda","en":"Alolan Diglett","alolan":true,"getshiny":true},
{"dex":51,"name":"Digdri","en":"Dugtrio","evolved":true},
{"dex":"51A","name":"Alola-Digdri","en":"Alolan Dugtrio","alolan":true,"evolved":true},
{"dex":52,"name":"Mauzi","en":"Meowth","getshiny":true},
{"dex":"52A","name":"Alola-Mauzi","en":"Alolan Meowth","alolan":true,"getshiny":true},
{"dex":"52G","name":"Galar-Mauzi","en":"Galarian Meowth","galarian":true,"getshiny":true},
{"dex":53,"name":"Snobilikat","en":"Persian","evolved":true},
{"dex":"53A","name":"Alola-Snobilikat","en":"Alolan Persian","alolan":true,"evolved":true},
{"dex":54,"name":"Enton","en":"Psyduck","getshiny":true},
{"dex":55,"name":"Entoron","en":"Golduck","evolved":true},
{"dex":56,"name":"Menki","en":"Mankey","getshiny":true},
{"dex":57,"name":"Rasaff","en":"Primeape","evolved":true},
{"dex":58,"name":"Fukano","en":"Growlithe","getshiny":true},
{"dex":"58H","name":"Hisui-Fukano","en":"Hisuian Growlithe","hisuian":true},
{"dex":59,"name":"Arkani","en":"Arcanine","evolved":true,"getshiny":true},
{"dex":"59H","name":"Hisui-Arkani","en":"Hisuian Arcanine","hisuian":true,"evolved":true},
{"dex":60,"name":"Quapsel","en":"Poliwag","getshiny":true},
{"dex":61,"name":"Quaputzi","en":"Poliwhirl","evolved":true,"getshiny":true},
{"dex":62,"name":"Quappo","en":"Poliwrath","evolved":true},
{"dex":63,"name":"Abra","getshiny":true},
{"dex":64,"name":"Kadabra","evolved":true},
{"dex":65,"name":"Simsala","en":"Alakazam","evolved":true,"getshiny":true},
{"dex":66,"name":"Machollo","en":"Machop","getshiny":true},
{"dex":67,"name":"Maschock","en":"Machoke","evolved":true},
{"dex":68,"name":"Machomei","en":"Machamp","evolved":true},
{"dex":69,"name":"Knofensa","en":"Bellsprout","getshiny":true},
{"dex":70,"name":"Ultrigaria","en":"Weepinbell","evolved":true},
{"dex":71,"name":"Sarzenia","en":"Victreebel","evolved":true},
{"dex":72,"name":"Tentacha","en":"Tentacool","getshiny":true},
{"dex":73,"name":"Tentoxa","en":"Tentacruel","evolved":true},
{"dex":74,"name":"Kleinstein","en":"Geodude","getshiny":true},
{"dex":"74A","name":"Alola-Kleinstein","en":"Alolan Geodude","alolan":true,"getshiny":true},
{"dex":75,"name":"Georok","en":"Graveler","evolved":true},
{"dex":"75A","name":"Alola-Georok","en":"Alolan Graveler","alolan":true,"evolved":true},
{"dex":76,"name":"Geowaz","en":"Golem","evolved":true},
{"dex":"76A","name":"Alola-Geowaz","en":"Alolan Golem","alolan":true,"evolved":true},
{"dex":77,"name":"Ponita","en":"Ponyta","getshiny":true},
{"dex":"77G","name":"Galar-Ponita","en":"Galarian Ponyta","galarian":true,"getshiny":true},
{"dex":78,"name":"Gallopa","en":"Rapidash","evolved":true},
{"dex":"78G","name":"Galar-Gallopa","en":"Galarian Rapidash","evolved":true,"galarian":true},
{"dex":79,"name":"Flegmon","en":"Slowpoke","getshiny":true},
{"dex":"79G","name":"Galar-Flegmon","en":"Galarian Slowpoke","galarian":true,"getshiny":true},
{"dex":80,"name":"Lahmus","en":"Slowbro","evolved":true,"getshiny":true},
{"dex":"80G","name":"Galar-Lahmus","en":"Galarian Slowbro","evolved":true,"galarian":true},
{"dex":81,"name":"Magnetilo","en":"Magnemite","getshiny":true},
{"dex":82,"name":"Magneton","evolved":true},
{"dex":83,"name":"Porenta","en":"Farfetch'd","regional":true,"getshiny":true},
{"dex":"83G","name":"Galar-Porenta","en":"Galarian Farfetch'd","galarian":true,"getshiny":true},
{"dex":84,"name":"Dodu","en":"Doduo","getshiny":true},
{"dex":85,"name":"Dodri","en":"Dodrio","evolved":true},
{"dex":86,"name":"Jurob","en":"Seel","getshiny":true},
{"dex":87,"name":"Jugong","en":"Dewgong","evolved":true},
{"dex":88,"name":"Sleima","en":"Grimer","getshiny":true},
{"dex":"88A","name":"Alola-Sleima","en":"Alolan Grimer","alolan":true,"getshiny":true},
{"dex":89,"name":"Sleimok","en":"Muk","evolved":true},
{"dex":"89A","name":"Alola-Sleimok","en":"Alolan Muk","alolan":true,"evolved":true},
{"dex":90,"name":"Muschas","en":"Shellder","getshiny":true},
{"dex":91,"name":"Austos","en":"Cloyster","evolved":true},
{"dex":92,"name":"Nebulak","en":"Gastly"},
{"dex":93,"name":"Alpollo","en":"Haunter","evolved":true,"getshiny":true},
{"dex":94,"name":"Gengar","evolved":true,"getshiny":true},
{"dex":95,"name":"Onix","getshiny":true},
{"dex":96,"name":"Traumato","en":"Drowzee","getshiny":true},
{"dex":97,"name":"Hypno","evolved":true},
{"dex":98,"name":"Krabby","getshiny":true},
{"dex":99,"name":"Kingler","evolved":true},
{"dex":100,"name":"Voltobal","en":"Voltorb","getshiny":true},
{"dex":"100H","name":"Hisui-Voltobal","en":"Hisuian Voltorb","hisuian":true},
{"dex":101,"name":"Lektrobal","en":"Electrode","evolved":true},
{"dex":"101H","name":"Hisui-Lektrobal","en":"Hisuian Electrode","hisuian":true,"evolved":true},
{"dex":102,"name":"Owei","en":"Exeggcute","getshiny":true},
{"dex":103,"name":"Kokowei","en":"Exeggutor","evolved":true},
{"dex":"103A","name":"Alola-Kokowei","en":"Alolan Exeggutor","alolan":true,"evolved":true,"getshiny":true},
{"dex":104,"name":"Tragosso","en":"Cubone","getshiny":true},
{"dex":105,"name":"Knogga","en":"Marowak","evolved":true},
{"dex":"105A","name":"Alola-Knogga","en":"Alolan Marowak","alolan":true,"evolved":true,"getshiny":true},
{"dex":106,"name":"Kicklee","en":"Hitmonlee","getshiny":true},
{"dex":107,"name":"Nockchan","en":"Hitmonchan","getshiny":true},
{"dex":108,"name":"Schlurp","en":"Lickitung","getshiny":true},
{"dex":109,"name":"Smogon","en":"Koffing","getshiny":true},
{"dex":110,"name":"Smogmog","en":"Weezing","evolved":true},
{"dex":"110G","name":"Galar-Smogmog","en":"Galarian Weezing","evolved":true,"galarian":true,"getshiny":true},
{"dex":111,"name":"Rihorn","en":"Rhyhorn","getshiny":true},
{"dex":112,"name":"Rizeros","en":"Rhydon","evolved":true},
{"dex":113,"name":"Chaneira","en":"Chansey","getshiny":true},
{"dex":114,"name":"Tangela","getshiny":true},
{"dex":115,"name":"Kangama","en":"Kangaskhan","regional":true,"getshiny":true},
{"dex":116,"name":"Seeper","en":"Horsea","getshiny":true},
{"dex":117,"name":"Seedra","en":"Seadra","evolved":true,"getshiny":true},
{"dex":118,"name":"Goldini","en":"Goldeen","getshiny":true},
{"dex":119,"name":"Golking","en":"Seaking","evolved":true},
{"dex":120,"name":"Sterndu","en":"Staryu","getshiny":true},
{"dex":121,"name":"Starmie","evolved":true},
{"dex":122,"name":"Pantimos","en":"Mr. Mime","regional":true,"getshiny":true},
{"dex":"122G","name":"Galar-Pantimos","en":"Galarian Mr. Mime","galarian":true,"getshiny":true},
{"dex":123,"name":"Sichlor","en":"Scyther","getshiny":true},
{"dex":124,"name":"Rossana","en":"Jynx","getshiny":true},
{"dex":125,"name":"Elektek","en":"Electabuzz","getshiny":true},
{"dex":126,"name":"Magmar","getshiny":true},
{"dex":127,"name":"Pinsir","getshiny":true},
{"dex":128,"name":"Tauros","regional":true,"getshiny":true},
{"dex":"128PA","name":"Paldea-Tauros (Flutenvariante)","en":"Paldean Tauros (Aqua Breed)","paldean":true},
{"dex":"128PB","name":"Paldea-Tauros (Flammenvariante)","en":"Paldean Tauros (Blaze Breed)","paldean":true},
{"dex":"128PC","name":"Paldea-Tauros (Gefechtvariante)","en":"Paldean Tauros (Combat Breed)","paldean":true},
{"dex":129,"name":"Karpador","en":"Magikarp","getshiny":true},
{"dex":130,"name":"Garados","en":"Gyarados","evolved":true,"getshiny":true},
{"dex":131,"name":"Lapras","getshiny":true},
{"dex":132,"name":"Ditto","getshiny":true},
{"dex":133,"name":"Evoli","en":"Eevee","getshiny":true},
{"dex":134,"name":"Aquana","en":"Vaporeon","evolved":true},
{"dex":135,"name":"Blitza","en":"Jolteon","evolved":true},
{"dex":136,"name":"Flamara","en":"Flareon","evolved":true},
{"dex":137,"name":"Porygon","getshiny":true},
{"dex":138,"name":"Amonitas","en":"Omanyte","getshiny":true},
{"dex":139,"name":"Amoroso","en":"Omastar","evolved":true},
{"dex":140,"name":"Kabuto","getshiny":true},
{"dex":141,"name":"Kabutops","evolved":true},
{"dex":142,"name":"Aerodactyl","getshiny":true},
{"dex":143,"name":"Relaxo","en":"Snorlax","getshiny":true},
{"dex":144,"name":"Arktos","en":"Articuno","legendary":true,"getshiny":true},
{"dex":"144G","name":"Galar-Arktos","en":"Galarian Articuno","legendary":true,"galarian":true},
{"dex":"144SH","name":"Crypto-Arktos","en":"Shadow Articuno","shadow":true,"legendary":true,"getshiny":true},
{"dex":145,"name":"Zapdos","legendary":true,"getshiny":true},
{"dex":"145G","name":"Galar-Zapdos","en":"Galarian Zapdos","legendary":true,"galarian":true},
{"dex":"145SH","name":"Crypto-Zapdos","en":"Shadow Zapdos","shadow":true,"legendary":true,"getshiny":true},
{"dex":146,"name":"Lavados","en":"Moltres","legendary":true,"getshiny":true},
{"dex":"146G","name":"Galar-Lavados","en":"Galarian Moltres","legendary":true,"galarian":true},
{"dex":"146SH","name":"Crypto-Lavados","en":"Shadow Moltres","shadow":true,"legendary":true,"getshiny":true},
{"dex":147,"name":"Dratini","getshiny":true},
{"dex":148,"name":"Dragonir","en":"Dragonair","evolved":true},
{"dex":149,"name":"Dragoran","en":"Dragonite","evolved":true},
{"dex":150,"name":"Mewtu","en":"Mewtwo","legendary":true,"getshiny":true},
{"dex":"150R","name":"Mewtu (Rüstung)","de":"Mewtu in Rüstung","en":"Armored Mewtwo","legendary":true},
{"dex":"150SH","name":"Crypto-Mewtu","en":"Shadow Mewtwo","shadow":true,"legendary":true,"getshiny":true},
{"dex":151,"name":"Mew","mythical":true},
{"dex":152,"name":"Endivie","en":"Chikorita","getshiny":true},
{"dex":153,"name":"Lorblatt","en":"Bayleef","evolved":true},
{"dex":154,"name":"Meganie","en":"Meganium","evolved":true},
{"dex":155,"name":"Feurigel","en":"Cyndaquil","getshiny":true},
{"dex":156,"name":"Igelavar","en":"Quilava","evolved":true},
{"dex":157,"name":"Tornupto","en":"Typhlosion","evolved":true},
{"dex":"157H","name":"Hisui-Tornupto","en":"Hisuian Typhlosion","hisuian":true,"evolved":true},
{"dex":158,"name":"Karnimani","en":"Totodile","getshiny":true},
{"dex":159,"name":"Tyracroc","en":"Croconaw","evolved":true},
{"dex":160,"name":"Impergator","en":"Feraligatr","evolved":true},
{"dex":161,"name":"Wiesor","en":"Sentret","getshiny":true},
{"dex":162,"name":"Wiesenior","en":"Furret","evolved":true},
{"dex":163,"name":"Hoothoot","getshiny":true},
{"dex":164,"name":"Noctuh","en":"Noctowl","evolved":true},
{"dex":165,"name":"Ledyba","getshiny":true},
{"dex":166,"name":"Ledian","evolved":true},
{"dex":167,"name":"Webarak","en":"Spinarak","getshiny":true},
{"dex":168,"name":"Ariados","evolved":true},
{"dex":169,"name":"Iksbat","en":"Crobat","evolved":true},
{"dex":170,"name":"Lampi","en":"Chinchou","getshiny":true},
{"dex":171,"name":"Lanturn","evolved":true},
{"dex":172,"name":"Pichu","baby":true,"getshiny":true},
{"dex":173,"name":"Pii","en":"Cleffa","baby":true,"getshiny":true},
{"dex":174,"name":"Fluffeluff","en":"Igglybuff","baby":true,"getshiny":true},
{"dex":175,"name":"Togepi","baby":true,"getshiny":true},
{"dex":176,"name":"Togetic","getshiny":true},
{"dex":177,"name":"Natu","getshiny":true},
{"dex":178,"name":"Xatu","evolved":true},
{"dex":179,"name":"Voltilamm","en":"Mareep","getshiny":true},
{"dex":180,"name":"Waaty","en":"Flaaffy","evolved":true},
{"dex":181,"name":"Ampharos","evolved":true,"getshiny":true},
{"dex":182,"name":"Blubella","en":"Bellossom","evolved":true},
{"dex":183,"name":"Marill","getshiny":true},
{"dex":184,"name":"Azumarill","evolved":true},
{"dex":185,"name":"Mogelbaum","en":"Sudowoodo","getshiny":true},
{"dex":186,"name":"Quaxo","en":"Politoed","evolved":true},
{"dex":187,"name":"Hoppspross","en":"Hoppip","getshiny":true},
{"dex":188,"name":"Hubelupf","en":"Skiploom","evolved":true},
{"dex":189,"name":"Papungha","en":"Jumpluff","evolved":true},
{"dex":190,"name":"Griffel","en":"Aipom","getshiny":true},
{"dex":191,"name":"Sonnkern","en":"Sunkern","getshiny":true},
{"dex":192,"name":"Sonnflora","en":"Sunflora","evolved":true},
{"dex":193,"name":"Yanma","getshiny":true},
{"dex":194,"name":"Felino","en":"Wooper","getshiny":true},
{"dex":"194P","name":"Paldea-Felino","en":"Paldean Wooper","paldean":true},
{"dex":195,"name":"Morlord","en":"Quagsire","evolved":true},
{"dex":196,"name":"Psiana","en":"Espeon","evolved":true,"getshiny":true},
{"dex":197,"name":"Nachtara","en":"Umbreon","evolved":true,"getshiny":true},
{"dex":198,"name":"Kramurx","en":"Murkrow","getshiny":true},
{"dex":199,"name":"Laschoking","en":"Slowking","evolved":true},
{"dex":"199G","name":"Galar-Laschoking","en":"Galarian Slowking","evolved":true,"galarian":true},
{"dex":200,"name":"Traunfugil","en":"Misdreavus","getshiny":true},
{"dex":201,"name":"Icognito","en":"Unown"},
{"dex":"201A","name":"Icognito A","en":"Unown A"},
{"dex":"201B","name":"Icognito B","en":"Unown B"},
{"dex":"201C","name":"Icognito C","en":"Unown C"},
{"dex":"201D","name":"Icognito D","en":"Unown D"},
{"dex":"201E","name":"Icognito E","en":"Unown E"},
{"dex":"201F","name":"Icognito F","en":"Unown F"},
{"dex":"201G","name":"Icognito G","en":"Unown G"},
{"dex":"201H","name":"Icognito H","en":"Unown H"},
{"dex":"201I","name":"Icognito I","en":"Unown I"},
{"dex":"201J","name":"Icognito J","en":"Unown J"},
{"dex":"201K","name":"Icognito K","en":"Unown K"},
{"dex":"201L","name":"Icognito L","en":"Unown L"},
{"dex":"201M","name":"Icognito M","en":"Unown M"},
{"dex":"201N","name":"Icognito N","en":"Unown N"},
{"dex":"201O","name":"Icognito O","en":"Unown O"},
{"dex":"201P","name":"Icognito P","en":"Unown P"},
{"dex":"201Q","name":"Icognito Q","en":"Unown Q"},
{"dex":"201R","name":"Icognito R","en":"Unown R"},
{"dex":"201S","name":"Icognito S","en":"Unown S"},
{"dex":"201T","name":"Icognito T","en":"Unown T"},
{"dex":"201U","name":"Icognito U","en":"Unown U"},
{"dex":"201V","name":"Icognito V","en":"Unown V"},
{"dex":"201W","name":"Icognito W","en":"Unown W"},
{"dex":"201X","name":"Icognito X","en":"Unown X"},
{"dex":"201Y","name":"Icognito Y","en":"Unown Y"},
{"dex":"201Z","name":"Icognito Z","en":"Unown Z"},
{"dex":"201Em","name":"Icognito !","en":"Unown !"},
{"dex":"201Qm","name":"Icognito ?","en":"Unown ?"},
{"dex":202,"name":"Woingenau","en":"Wobbuffet","getshiny":true},
{"dex":203,"name":"Girafarig","getshiny":true},
{"dex":204,"name":"Tannza","en":"Pineco","getshiny":true},
{"dex":205,"name":"Forstellka","en":"Forretress","evolved":true},
{"dex":206,"name":"Dummisel","en":"Dunsparce","getshiny":true},
{"dex":207,"name":"Skorgla","en":"Gligar","getshiny":true},
{"dex":208,"name":"Stahlos","en":"Steelix","evolved":true,"getshiny":true},
{"dex":209,"name":"Snubbull","getshiny":true},
{"dex":210,"name":"Granbull","evolved":true},
{"dex":211,"name":"Baldorfish","en":"Qwilfish","getshiny":true},
{"dex":"211H","name":"Hisui-Baldorfish","en":"Hisuian Qwilfish","hisuian":true},
{"dex":212,"name":"Scherox","en":"Scizor","evolved":true,"getshiny":true},
{"dex":213,"name":"Pottrott","en":"Shuckle","getshiny":true},
{"dex":214,"name":"Skaraborn","en":"Heracross","regional":true,"getshiny":true},
{"dex":215,"name":"Sniebel","en":"Sneasel","getshiny":true},
{"dex":"215H","name":"Hisui-Sniebel","en":"Hisuian Sneasel","hisuian":true},
{"dex":216,"name":"Teddiursa","getshiny":true},
{"dex":217,"name":"Ursaring","evolved":true},
{"dex":218,"name":"Schneckmag","en":"Slugma","getshiny":true},
{"dex":219,"name":"Magcargo","evolved":true},
{"dex":220,"name":"Quiekel","en":"Swinub","getshiny":true},
{"dex":221,"name":"Keifel","en":"Piloswine","evolved":true},
{"dex":222,"name":"Corasonn","en":"Corsola","regional":true,"getshiny":true},
{"dex":"222G","name":"Galar-Corasonn","en":"Galarian Corsola","regional":true,"galarian":true},
{"dex":223,"name":"Remoraid","getshiny":true},
{"dex":224,"name":"Octillery","evolved":true},
{"dex":225,"name":"Botogel","en":"Delibird","getshiny":true},
{"dex":226,"name":"Mantax","en":"Mantine","getshiny":true},
{"dex":227,"name":"Panzaeron","en":"Skarmory","getshiny":true},
{"dex":228,"name":"Hunduster","en":"Houndour","getshiny":true},
{"dex":229,"name":"Hundemon","en":"Houndoom","evolved":true,"getshiny":true},
{"dex":230,"name":"Seedraking","en":"Kingdra","evolved":true},
{"dex":231,"name":"Phanpy","getshiny":true},
{"dex":232,"name":"Donphan","evolved":true},
{"dex":233,"name":"Porygon2","evolved":true},
{"dex":234,"name":"Damhirplex","en":"Stantler","getshiny":true},
{"dex":235,"name":"Farbeagle","en":"Smeargle"},
{"dex":236,"name":"Rabauz","en":"Tyrogue","baby":true,"getshiny":true},
{"dex":237,"name":"Kapoera","en":"Hitmontop","getshiny":true},
{"dex":238,"name":"Kussila","en":"Smoochum","baby":true,"getshiny":true},
{"dex":239,"name":"Elekid","baby":true,"getshiny":true},
{"dex":240,"name":"Magby","baby":true,"getshiny":true},
{"dex":241,"name":"Miltank","getshiny":true},
{"dex":242,"name":"Heiteira","en":"Blissey","evolved":true},
{"dex":243,"name":"Raikou","legendary":true,"getshiny":true},
{"dex":244,"name":"Entei","legendary":true,"getshiny":true},
{"dex":245,"name":"Suicune","legendary":true,"getshiny":true},
{"dex":246,"name":"Larvitar","getshiny":true},
{"dex":247,"name":"Pupitar","evolved":true},
{"dex":248,"name":"Despotar","en":"Tyranitar","evolved":true,"getshiny":true},
{"dex":249,"name":"Lugia","legendary":true,"getshiny":true},
{"dex":250,"name":"Ho-Oh","legendary":true,"getshiny":true},
{"dex":251,"name":"Celebi","mythical":true},
{"dex":252,"name":"Geckarbor","en":"Treecko","getshiny":true},
{"dex":253,"name":"Reptain","en":"Grovyle","evolved":true},
{"dex":254,"name":"Gewaldro","en":"Sceptile","evolved":true,"getshiny":true},
{"dex":255,"name":"Flemmli","en":"Torchic","getshiny":true},
{"dex":256,"name":"Jungglut","en":"Combusken","evolved":true},
{"dex":257,"name":"Lohgock","en":"Blaziken","evolved":true,"getshiny":true},
{"dex":258,"name":"Hydropi","en":"Mudkip","getshiny":true},
{"dex":259,"name":"Moorabbel","en":"Marshtomp","evolved":true},
{"dex":260,"name":"Sumpex","en":"Swampert","evolved":true,"getshiny":true},
{"dex":261,"name":"Fiffyen","en":"Poochyena","getshiny":true},
{"dex":262,"name":"Magnayen","en":"Mightyena","evolved":true},
{"dex":263,"name":"Zigzachs","en":"Zigzagoon","getshiny":true},
{"dex":"263G","name":"Galar-Zigzachs","en":"Galarian Zigzagoon","galarian":true,"getshiny":true},
{"dex":264,"name":"Geradaks","en":"Linoone","evolved":true},
{"dex":"264G","name":"Galar-Geradaks","en":"Galarian Linoone","evolved":true,"galarian":true},
{"dex":265,"name":"Waumpel","en":"Wurmple","getshiny":true},
{"dex":266,"name":"Schaloko","en":"Silcoon","evolved":true},
{"dex":267,"name":"Papinella","en":"Beautifly","evolved":true},
{"dex":268,"name":"Panekon","en":"Cascoon","evolved":true},
{"dex":269,"name":"Pudox","en":"Dustox","evolved":true},
{"dex":270,"name":"Loturzel","en":"Lotad","getshiny":true},
{"dex":271,"name":"Lombrero","en":"Lombre","evolved":true},
{"dex":272,"name":"Kappalores","en":"Ludicolo","evolved":true},
{"dex":273,"name":"Samurzel","en":"Seedot","getshiny":true},
{"dex":274,"name":"Blanas","en":"Nuzleaf","evolved":true},
{"dex":275,"name":"Tengulist","en":"Shiftry","evolved":true},
{"dex":276,"name":"Schwalbini","en":"Taillow","getshiny":true},
{"dex":277,"name":"Schwalboss","en":"Swellow","evolved":true},
{"dex":278,"name":"Wingull","getshiny":true},
{"dex":279,"name":"Pelipper","evolved":true},
{"dex":280,"name":"Trasla","en":"Ralts", "getshiny":true},
{"dex":281,"name":"Kirlia","evolved":true,"getshiny":true},
{"dex":282,"name":"Guardevoir","en":"Gardevoir","evolved":true},
{"dex":283,"name":"Gehweiher","en":"Surskit","getshiny":true},
{"dex":284,"name":"Maskeregen","en":"Masquerain","evolved":true},
{"dex":285,"name":"Knilz","en":"Shroomish","getshiny":true},
{"dex":286,"name":"Kapilz","en":"Breloom","evolved":true},
{"dex":287,"name":"Bummelz","en":"Slakoth","getshiny":true},
{"dex":288,"name":"Muntier","en":"Vigoroth","evolved":true},
{"dex":289,"name":"Letarking","en":"Slaking","evolved":true},
{"dex":290,"name":"Nincada","getshiny":true},
{"dex":291,"name":"Ninjask","evolved":true},
{"dex":292,"name":"Ninjatom","en":"Shedinja","evolved":true,"getshiny":true},
{"dex":293,"name":"Flurmel","en":"Whismur","getshiny":true},
{"dex":294,"name":"Krakeelo","en":"Loudred","evolved":true},
{"dex":295,"name":"Krawumms","en":"Exploud","evolved":true},
{"dex":296,"name":"Makuhita","getshiny":true},
{"dex":297,"name":"Hariyama","evolved":true},
{"dex":298,"name":"Azurill","baby":true,"getshiny":true},
{"dex":299,"name":"Nasgnet","en":"Nosepass","getshiny":true},
{"dex":300,"name":"Eneco","en":"Skitty","getshiny":true},
{"dex":301,"name":"Enecoro","en":"Delcatty","evolved":true},
{"dex":302,"name":"Zobiris","en":"Sableye","getshiny":true},
{"dex":303,"name":"Flunkifer","en":"Mawile","getshiny":true},
{"dex":304,"name":"Stollunior","en":"Aron","getshiny":true},
{"dex":305,"name":"Stollrak","en":"Lairon","evolved":true},
{"dex":306,"name":"Stolloss","en":"Aggron","evolved":true,"getshiny":true},
{"dex":307,"name":"Meditie","en":"Meditite","getshiny":true},
{"dex":308,"name":"Meditalis","en":"Medicham","evolved":true,"getshiny":true},
{"dex":309,"name":"Frizelbliz","en":"Electrike","getshiny":true},
{"dex":310,"name":"Voltenso","en":"Manectric","evolved":true,"getshiny":true},
{"dex":311,"name":"Plusle","getshiny":true},
{"dex":312,"name":"Minun","getshiny":true},
{"dex":313,"name":"Volbeat","regional":true,"getshiny":true},
{"dex":314,"name":"Illumise","regional":true,"getshiny":true},
{"dex":315,"name":"Roselia","getshiny":true},
{"dex":316,"name":"Schluppuck","en":"Gulpin","getshiny":true},
{"dex":317,"name":"Schlukwech","en":"Swalot","evolved":true},
{"dex":318,"name":"Kanivanha","en":"Carvanha","getshiny":true},
{"dex":319,"name":"Tohaido","en":"Sharpedo","evolved":true},
{"dex":320,"name":"Wailmer","getshiny":true},
{"dex":321,"name":"Wailord","evolved":true},
{"dex":322,"name":"Camaub","en":"Numel","getshiny":true},
{"dex":323,"name":"Camerupt","evolved":true},
{"dex":324,"name":"Qurtel","en":"Torkoal","regional":true,"getshiny":true},
{"dex":325,"name":"Spoink","getshiny":true},
{"dex":326,"name":"Groink","en":"Grumpig","evolved":true},
{"dex":327,"name":"Pandir","en":"Spinda","getshiny":true},
{"dex":328,"name":"Knacklion","en":"Trapinch","getshiny":true},
{"dex":329,"name":"Vibrava","evolved":true},
{"dex":330,"name":"Libelldra","en":"Flygon","evolved":true},
{"dex":331,"name":"Tuska","en":"Cacnea","getshiny":true},
{"dex":332,"name":"Noktuska","en":"Cacturne","evolved":true},
{"dex":333,"name":"Wablu","en":"Swablu","getshiny":true},
{"dex":334,"name":"Altaria","evolved":true,"getshiny":true},
{"dex":335,"name":"Sengo","en":"Zangoose","regional":true,"getshiny":true},
{"dex":336,"name":"Vipitis","en":"Seviper","regional":true,"getshiny":true},
{"dex":337,"name":"Lunastein","en":"Lunatone","regional":true,"getshiny":true},
{"dex":338,"name":"Sonnfel","en":"Solrock","regional":true,"getshiny":true},
{"dex":339,"name":"Schmerbe","en":"Barboach","getshiny":true},
{"dex":340,"name":"Welsar","en":"Whiscash","evolved":true},
{"dex":341,"name":"Krebscorps","en":"Corphish","getshiny":true},
{"dex":342,"name":"Krebutack","en":"Crawdaunt","evolved":true},
{"dex":343,"name":"Puppance","en":"Baltoy","getshiny":true},
{"dex":344,"name":"Lepumentas","en":"Claydol","evolved":true},
{"dex":345,"name":"Liliep","en":"Lileep","getshiny":true},
{"dex":346,"name":"Wielie","en":"Cradily","evolved":true},
{"dex":347,"name":"Anorith","getshiny":true},
{"dex":348,"name":"Armaldo","evolved":true},
{"dex":349,"name":"Barschwa","en":"Feebas","getshiny":true},
{"dex":350,"name":"Milotic","evolved":true},
{"dex":351,"name":"Formeo","en":"Castform","getshiny":true},
{"dex":"351I","name":"Formeo (Schnee)","de":"Formeo (Schneeform)","en":"Castform (Snowy Form)","getshiny":true},
{"dex":"351R","name":"Formeo (Regen)","de":"Formeo (Regenform)","en":"Castform (Rainy Form)","getshiny":true},
{"dex":"351S","name":"Formeo (Sonne)","de":"Formeo (Sonnenform)","en":"Castform (Sunny Form)","getshiny":true},
{"dex":352,"name":"Kecleon","getshiny":true},
{"dex":353,"name":"Shuppet","getshiny":true},
{"dex":354,"name":"Banette","evolved":true,"getshiny":true},
{"dex":355,"name":"Zwirrlicht","en":"Duskull","getshiny":true},
{"dex":356,"name":"Zwirrklop","en":"Dusclops","evolved":true},
{"dex":357,"name":"Tropius","regional":true,"getshiny":true},
{"dex":358,"name":"Palimpalim","en":"Chimecho","getshiny":true},
{"dex":359,"name":"Absol","getshiny":true},
{"dex":360,"name":"Isso","en":"Wynaut","baby":true,"getshiny":true},
{"dex":361,"name":"Schneppke","en":"Snorunt","getshiny":true},
{"dex":362,"name":"Firnontor","en":"Glalie","evolved":true,"getshiny":true},
{"dex":363,"name":"Seemops","en":"Spheal","getshiny":true},
{"dex":364,"name":"Seejong","en":"Sealeo","evolved":true},
{"dex":365,"name":"Walraisa","en":"Walrein","evolved":true},
{"dex":366,"name":"Perlu","en":"Clamperl","getshiny":true},
{"dex":367,"name":"Aalabyss","en":"Huntail","evolved":true},
{"dex":368,"name":"Saganabyss","en":"Gorebyss","evolved":true},
{"dex":369,"name":"Relicanth","regional":true,"getshiny":true},
{"dex":370,"name":"Liebiskus","en":"Luvdisc","getshiny":true},
{"dex":371,"name":"Kindwurm","en":"Bagon","getshiny":true},
{"dex":372,"name":"Draschel","en":"Shelgon","evolved":true},
{"dex":373,"name":"Brutalanda","en":"Salamence","evolved":true},
{"dex":374,"name":"Tanhel","en":"Beldum","getshiny":true},
{"dex":375,"name":"Metang","evolved":true},
{"dex":376,"name":"Metagross","evolved":true},
{"dex":377,"name":"Regirock","legendary":true,"getshiny":true},
{"dex":378,"name":"Regice","legendary":true,"getshiny":true},
{"dex":379,"name":"Registeel","legendary":true,"getshiny":true},
{"dex":380,"name":"Latias","legendary":true,"getshiny":true},
{"dex":381,"name":"Latios","legendary":true,"getshiny":true},
{"dex":382,"name":"Kyogre","legendary":true,"getshiny":true},
{"dex":383,"name":"Groudon","legendary":true,"getshiny":true},
{"dex":384,"name":"Rayquaza","legendary":true,"getshiny":true},
{"dex":385,"name":"Jirachi","mythical":true},
{"dex":386,"name":"Deoxys (Normal)","de":"Deoxys (Normalform)","en":"Deoxys (Normal Forme)","mythical":true,"getshiny":true},
{"dex":"386A","name":"Deoxys (Angriff)","de":"Deoxys (Angriffsform)","en":"Deoxys (Attack Forme)","mythical":true,"getshiny":true},
{"dex":"386D","name":"Deoxys (Verteidigung)","de":"Deoxys (Verteidigungsform)","en":"Deoxys (Defense Forme)","mythical":true,"getshiny":true},
{"dex":"386S","name":"Deoxys (Initiative)","de":"Deoxys (Initiativeform)","en":"Deoxys (Speed Forme)","mythical":true,"getshiny":true},
{"dex":387,"name":"Chelast","en":"Turtwig","getshiny":true},
{"dex":388,"name":"Chelcarain","en":"Grotle","evolved":true},
{"dex":389,"name":"Chelterrar","en":"Torterra","evolved":true},
{"dex":390,"name":"Panflam","en":"Chimchar","getshiny":true},
{"dex":391,"name":"Panpyro","en":"Monferno","evolved":true},
{"dex":392,"name":"Panferno","en":"Infernape","evolved":true},
{"dex":393,"name":"Plinfa","en":"Piplup","getshiny":true},
{"dex":394,"name":"Pliprin","en":"Prinplup","evolved":true},
{"dex":395,"name":"Impoleon","en":"Empoleon","evolved":true},
{"dex":396,"name":"Staralili","en":"Starly","getshiny":true},
{"dex":397,"name":"Staravia","evolved":true},
{"dex":398,"name":"Staraptor","evolved":true},
{"dex":399,"name":"Bidiza","en":"Bidoof","getshiny":true},
{"dex":400,"name":"Bidifas","en":"Bibarel","evolved":true},
{"dex":401,"name":"Zirpurze","en":"Kricketot","getshiny":true},
{"dex":402,"name":"Zirpeise","en":"Kricketune","evolved":true},
{"dex":403,"name":"Sheinux","en":"Shinx","getshiny":true},
{"dex":404,"name":"Luxio","evolved":true},
{"dex":405,"name":"Luxtra","en":"Luxray","evolved":true},
{"dex":406,"name":"Knospi","en":"Budew","baby":true,"getshiny":true},
{"dex":407,"name":"Roserade","evolved":true},
{"dex":408,"name":"Koknodon","en":"Cranidos","getshiny":true},
{"dex":409,"name":"Rameidon","en":"Rampardos","evolved":true},
{"dex":410,"name":"Schilterus","en":"Shieldon","getshiny":true},
{"dex":411,"name":"Bollterus","en":"Bastiodon","evolved":true},
{"dex":412,"name":"Burmy (Pflanze)","de":"Burmy (Pflanzenumhang)","en":"Burmy (Plant Cloak)","getshiny":true},
{"dex":"412S","name":"Burmy (Sand)","de":"Burmy (Sandumhang)","en":"Burmy (Sandy Cloak)","getshiny":true},
{"dex":"412T","name":"Burmy (Lumpen)","de":"Burmy (Lumpenumhang)","en":"Burmy (Trash Cloak)","getshiny":true},
{"dex":413,"name":"Burmadame (Pflanze)","de":"Burmadame (Pflanzenumhang)","en":"Wormadam (Plant Cloak)","evolved":true},
{"dex":"413S","name":"Burmadame (Sand)","de":"Burmadame (Sandumhang)","en":"Wormadam (Sandy Cloak)","evolved":true},
{"dex":"413T","name":"Burmadame (Lumpen)","de":"Burmadame (Lumpenumhang)","en":"Wormadam (Trash Cloak)","evolved":true},
{"dex":414,"name":"Moterpel","en":"Mothim","evolved":true},
{"dex":415,"name":"Wadribie","en":"Combee","getshiny":true},
{"dex":416,"name":"Honweisel","en":"Vespiquen","evolved":true},
{"dex":417,"name":"Pachirisu","regional":true},
{"dex":418,"name":"Bamelin","en":"Buizel","getshiny":true},
{"dex":419,"name":"Bojelin","en":"Floatzel","evolved":true},
{"dex":420,"name":"Kikugi","en":"Cherubi","getshiny":true},
{"dex":421,"name":"Kinoso (Bewölkt)","de":"Kinoso (Wolkenform)","en":"Cherrim (Overcast Form)","evolved":true},
{"dex":"421S","name":"Kinoso (Sonne)","de":"Kinoso (Sonnenform)","en":"Cherrim (Sunshine Form)","evolved":true},
{"dex":422,"name":"Schalellos","en":"Shellos","getshiny":true},
{"dex":"422W","name":"Schalellos (West)","de":"Schalellos (Westliches Meer)","en":"Shellos (West Sea)","regional":true,"getshiny":true},
{"dex":"422E","name":"Schalellos (Ost)","de":"Schalellos (Östliches Meer)","en":"Shellos (East Sea)","regional":true,"getshiny":true},
{"dex":423,"name":"Gastrodon","evolved":true},
{"dex":424,"name":"Ambidiffel","en":"Ambipom","evolved":true},
{"dex":425,"name":"Driftlon","en":"Drifloon","getshiny":true},
{"dex":426,"name":"Drifzepeli","en":"Drifblim","evolved":true,"getshiny":true},
{"dex":427,"name":"Haspiror","en":"Buneary","getshiny":true},
{"dex":428,"name":"Schlapor","en":"Lopunny","evolved":true,"getshiny":true},
{"dex":429,"name":"Traunmagil","en":"Mismagius","evolved":true},
{"dex":430,"name":"Kramshef","en":"Honchkrow","evolved":true},
{"dex":431,"name":"Charmian","en":"Glameow","getshiny":true},
{"dex":432,"name":"Shnurgarst","en":"Purugly","evolved":true},
{"dex":433,"name":"Klingplim","en":"Chingling","baby":true},
{"dex":434,"name":"Skunkapuh","en":"Stunky"},
{"dex":435,"name":"Skuntank","evolved":true},
{"dex":436,"name":"Bronzel","en":"Bronzor","getshiny":true},
{"dex":437,"name":"Bronzong","evolved":true},
{"dex":438,"name":"Mobai","en":"Bonsly","baby":true,"getshiny":true},
{"dex":439,"name":"Pantimimi","en":"Mime Jr.","baby":true,"regional":true,"getshiny":true},
{"dex":440,"name":"Wonneira","en":"Happiny","baby":true,"getshiny":true},
{"dex":441,"name":"Plaudagei","en":"Chatot","regional":true},
{"dex":442,"name":"Kryppuk","en":"Spiritomb","getshiny":true},
{"dex":443,"name":"Kaumalat","en":"Gible","getshiny":true},
{"dex":444,"name":"Knarksel","en":"Gabite","evolved":true},
{"dex":445,"name":"Knakrack","en":"Garchomp","evolved":true},
{"dex":446,"name":"Mampfaxo","en":"Munchlax","baby":true,"getshiny":true},
{"dex":447,"name":"Riolu","baby":true,"getshiny":true},
{"dex":448,"name":"Lucario"},
{"dex":449,"name":"Hippopotas","getshiny":true},
{"dex":450,"name":"Hippoterus","en":"Hippowdon","evolved":true},
{"dex":451,"name":"Pionskora","en":"Skorupi","getshiny":true},
{"dex":452,"name":"Piondragi","en":"Drapion","evolved":true},
{"dex":453,"name":"Glibunkel","en":"Croagunk","getshiny":true},
{"dex":454,"name":"Toxiquak","en":"Toxicroak","evolved":true},
{"dex":455,"name":"Venuflibis","en":"Carnivine","regional":true},
{"dex":456,"name":"Finneon","getshiny":true},
{"dex":457,"name":"Lumineon","evolved":true},
{"dex":458,"name":"Mantirps","en":"Mantyke","baby":true,"getshiny":true},
{"dex":459,"name":"Shnebedeck","en":"Snover","getshiny":true},
{"dex":460,"name":"Rexblisar","en":"Abomasnow","evolved":true,"getshiny":true},
{"dex":461,"name":"Snibunna","en":"Weavile","evolved":true},
{"dex":462,"name":"Magnezone","evolved":true},
{"dex":463,"name":"Schlurplek","en":"Lickilicky","evolved":true},
{"dex":464,"name":"Rihornior","en":"Rhyperior","evolved":true},
{"dex":465,"name":"Tangoloss","en":"Tangrowth","evolved":true},
{"dex":466,"name":"Elevoltek","en":"Electivire","evolved":true},
{"dex":467,"name":"Magbrant","en":"Magmortar","evolved":true},
{"dex":468,"name":"Togekiss","evolved":true},
{"dex":469,"name":"Yanmega","evolved":true},
{"dex":470,"name":"Folipurba","en":"Leafeon","evolved":true},
{"dex":471,"name":"Glaziola","en":"Glaceon","evolved":true,"getshiny":true},
{"dex":472,"name":"Skorgro","en":"Gliscor","evolved":true},
{"dex":473,"name":"Mamutel","en":"Mamoswine","evolved":true},
{"dex":474,"name":"Porygon-Z","evolved":true},
{"dex":475,"name":"Galagladi","en":"Gallade","evolved":true},
{"dex":476,"name":"Voluminas","en":"Probopass","evolved":true},
{"dex":477,"name":"Zwirrfinst","en":"Dusknoir","evolved":true},
{"dex":478,"name":"Frosdedje","en":"Froslass","evolved":true},
{"dex":479,"name":"Rotom"},
{"dex":"479F","name":"Rotom (Wirbel)","de":"Wirbel-Rotom","en":"Fan Rotom","legendary":true},
{"dex":"479H","name":"Rotom (Hitze)","de":"Hitze-Rotom","en":"Heat Rotom","legendary":true},
{"dex":"479I","name":"Rotom (Frost)","de":"Frost-Rotom","en":"Frost Rotom","legendary":true},
{"dex":"479M","name":"Rotom (Schneid)","de":"Schneid-Rotom","en":"Mow Rotom","legendary":true},
{"dex":"479W","name":"Rotom (Wasch)","de":"Wasch-Rotom","en":"Wash Rotom","legendary":true},
{"dex":480,"name":"Selfe","en":"Uxie","legendary":true,"regional":true,"getshiny":true},
{"dex":481,"name":"Vesprit","en":"Mesprit","legendary":true,"regional":true,"getshiny":true},
{"dex":482,"name":"Tobutz","en":"Azelf","legendary":true,"regional":true,"getshiny":true},
{"dex":483,"name":"Dialga","legendary":true,"getshiny":true},
{"dex":"483O","name":"Dialga (Urform)","en":"Dialga (Origin Forme)","legendary":true},
{"dex":484,"name":"Palkia","legendary":true,"getshiny":true},
{"dex":"484O","name":"Palkia (Urform)","en":"Palkia (Origin Forme)","legendary":true},
{"dex":485,"name":"Heatran","legendary":true,"getshiny":true},
{"dex":486,"name":"Regigigas","legendary":true,"getshiny":true},
{"dex":487,"name":"Giratina","de":"Giratina (Wandelform)","en":"Giratina (Altered Forme)","legendary":true,"getshiny":true},
{"dex":"487O","name":"Giratina (Urform)","de":"Giratina (Urform)","en":"Giratina (Origin Forme)","legendary":true,"getshiny":true},
{"dex":488,"name":"Cresselia","legendary":true,"getshiny":true},
{"dex":489,"name":"Phione","mythical":true},
{"dex":490,"name":"Manaphy","mythical":true},
{"dex":491,"name":"Darkrai","mythical":true,"getshiny":true},
{"dex":492,"name":"Shaymin (Land)","de":"Shaymin (Landform)","en":"Shaymin (Land Forme)","mythical":true},
{"dex":"492S","name":"Shaymin (Zenit)","de":"Shaymin (Zenitform)","en":"Shaymin (Sky Forme)","mythical":true},
{"dex":493,"name":"Arceus (Normal)","en":"Arceus (Normal type)","mythical":true},
{"dex":"493Fg","name":"Arceus (Kampf)","en":"Arceus (Fighting type)","mythical":true},
{"dex":"493Fl","name":"Arceus (Flug)","en":"Arceus (Flying type)","mythical":true},
{"dex":"493Po","name":"Arceus (Gift)","en":"Arceus (Poison type)","mythical":true},
{"dex":"493Gn","name":"Arceus (Boden)","en":"Arceus (Ground type)","mythical":true},
{"dex":"493Ro","name":"Arceus (Gestein)","en":"Arceus (Rock type)","mythical":true},
{"dex":"493Bu","name":"Arceus (Käfer)","en":"Arceus (Bug type)","mythical":true},
{"dex":"493Gh","name":"Arceus (Geist)","en":"Arceus (Ghost type)","mythical":true},
{"dex":"493St","name":"Arceus (Stahl)","en":"Arceus (Steel type)","mythical":true},
{"dex":"493Fi","name":"Arceus (Feuer)","en":"Arceus (Fire type)","mythical":true},
{"dex":"493Wa","name":"Arceus (Wasser)","en":"Arceus (Water type)","mythical":true},
{"dex":"493Gr","name":"Arceus (Pflanze)","en":"Arceus (Grass type)","mythical":true},
{"dex":"493El","name":"Arceus (Elektro)","en":"Arceus (Electric type)","mythical":true},
{"dex":"493Ps","name":"Arceus (Psycho)","en":"Arceus (Psychic type)","mythical":true},
{"dex":"493Ic","name":"Arceus (Eis)","en":"Arceus (Ice type)","mythical":true},
{"dex":"493Dr","name":"Arceus (Drache)","en":"Arceus (Dragon type)","mythical":true},
{"dex":"493Da","name":"Arceus (Unlicht)","en":"Arceus (Dark type)","mythical":true},
{"dex":"493Fa","name":"Arceus (Fee)","en":"Arceus (Fairy type)","mythical":true},
{"dex":494,"name":"Victini","mythical":true},
{"dex":495,"name":"Serpifeu","en":"Snivy","getshiny":true},
{"dex":496,"name":"Efoserp","en":"Servine","evolved":true},
{"dex":497,"name":"Serpiroyal","en":"Serperior","evolved":true},
{"dex":498,"name":"Floink","en":"Tepig","getshiny":true},
{"dex":499,"name":"Ferkokel","en":"Pignite","evolved":true},
{"dex":500,"name":"Flambirex","en":"Emboar","evolved":true},
{"dex":501,"name":"Ottaro","en":"Oshawott","getshiny":true},
{"dex":502,"name":"Zwottronin","en":"Dewott","evolved":true},
{"dex":503,"name":"Admurai","en":"Samurott","evolved":true},
{"dex":"503H","name":"Hisui-Admurai","en":"Hisuian Samurott","hisuian":true,"evolved":true},
{"dex":504,"name":"Nagelotz","en":"Patrat","getshiny":true},
{"dex":505,"name":"Kukmarda","en":"Watchog","evolved":true},
{"dex":506,"name":"Yorkleff","en":"Lillipup","getshiny":true},
{"dex":507,"name":"Terribark","en":"Herdier","evolved":true},
{"dex":508,"name":"Bissbark","en":"Stoutland","evolved":true},
{"dex":509,"name":"Felilou","en":"Purrloin","getshiny":true},
{"dex":510,"name":"Kleoparda","en":"Liepard","evolved":true},
{"dex":511,"name":"Vegimak","en":"Pansage","regional":true,"getshiny":true},
{"dex":512,"name":"Vegichita","en":"Simisage","evolved":true,"regional":true},
{"dex":513,"name":"Grillmak","en":"Pansear","regional":true,"getshiny":true},
{"dex":514,"name":"Grillchita","en":"Simisear","evolved":true,"regional":true},
{"dex":515,"name":"Sodamak","en":"Panpour","regional":true,"getshiny":true},
{"dex":516,"name":"Sodachita","en":"Simipour","evolved":true,"regional":true},
{"dex":517,"name":"Somniam","en":"Munna","getshiny":true},
{"dex":518,"name":"Somnivora","en":"Musharna","evolved":true},
{"dex":519,"name":"Dusselgurr","en":"Pidove","getshiny":true},
{"dex":520,"name":"Navitaub","en":"Tranquill","evolved":true},
{"dex":521,"name":"Fasasnob","en":"Unfezant","evolved":true},
{"dex":522,"name":"Elezeba","en":"Blitzle","getshiny":true},
{"dex":523,"name":"Zebritz","en":"Zebstrika","evolved":true},
{"dex":524,"name":"Kiesling","en":"Roggenrola","getshiny":true},
{"dex":525,"name":"Sedimantur","en":"Boldore","evolved":true},
{"dex":526,"name":"Brockoloss","en":"Gigalith","evolved":true},
{"dex":527,"name":"Fleknoil","en":"Woobat","getshiny":true},
{"dex":528,"name":"Fletiamo","en":"Swoobat","evolved":true},
{"dex":529,"name":"Rotomurf","en":"Drilbur","getshiny":true},
{"dex":530,"name":"Stalobor","en":"Excadrill","evolved":true},
{"dex":531,"name":"Ohrdoch","en":"Audino","getshiny":true},
{"dex":532,"name":"Praktibalk","en":"Timburr","getshiny":true},
{"dex":533,"name":"Strepoli","en":"Gurdurr","evolved":true},
{"dex":534,"name":"Meistagrif","en":"Conkeldurr","evolved":true},
{"dex":535,"name":"Schallquap","en":"Tympole","getshiny":true},
{"dex":536,"name":"Mebrana","en":"Palpitoad","evolved":true},
{"dex":537,"name":"Branawarz","en":"Seismitoad","evolved":true},
{"dex":538,"name":"Jiutesto","en":"Throh","regional":true,"getshiny":true},
{"dex":539,"name":"Karadonis","en":"Sawk","regional":true,"getshiny":true},
{"dex":540,"name":"Strawickl","en":"Sewaddle"},
{"dex":541,"name":"Folikon","en":"Swadloon","evolved":true},
{"dex":542,"name":"Matrifol","en":"Leavanny","evolved":true},
{"dex":543,"name":"Toxiped","en":"Venipede","getshiny":true},
{"dex":544,"name":"Rollum","en":"Whirlipede","evolved":true},
{"dex":545,"name":"Cerapendra","en":"Scolipede","evolved":true},
{"dex":546,"name":"Waumboll","en":"Cottonee","getshiny":true},
{"dex":547,"name":"Elfun","en":"Whimsicott","evolved":true},
{"dex":548,"name":"Lilminip","en":"Petilil","getshiny":true},
{"dex":549,"name":"Dressella","en":"Lilligant","evolved":true},
{"dex":"549H","name":"Hisui-Dressella","en":"Hisuian Lilligant","hisuian":true,"evolved":true},
{"dex":550,"name":"Barschuft (Rotlinig)","de":"Barschuft (Rotlinige Form)","en":"Basculin (Red-Striped Form)","regional":true},
{"dex":"550B","name":"Barschuft (Blaulinig)","de":"Barschuft (Blaulinige Form)","en":"Basculin (Blue-Striped Form)","regional":true},
{"dex":"550W","name":"Barschuft (Weißlinig)","de":"Barschuft (Weißlinige Form)","en":"Basculin (White-Striped Form)","hisuian":true},
{"dex":551,"name":"Ganovil","en":"Sandile"},
{"dex":552,"name":"Rokkaiman","en":"Krokorok","evolved":true},
{"dex":553,"name":"Rabigator","en":"Krookodile","evolved":true},
{"dex":554,"name":"Flampion","en":"Darumaka","getshiny":true},
{"dex":"554G","name":"Galar-Flampion","en":"Galarian Darumaka","galarian":true,"getshiny":true},
{"dex":555,"name":"Flampivian","en":"Darmanitan","evolved":true},
{"dex":"555G","name":"Galar-Flampivian","en":"Galarian Darmanitan","evolved":true,"galarian":true},
{"dex":"555Z","name":"Flampivian (Trance)","de":"Flampivian (Trance-Modus)","en":"Darmanitan (Zen Mode)","evolved":true},
{"dex":"555GZ","name":"Galar-Flampivian (Trance)","de":"Galar-Flampivian (Trance-Modus)","en":"Galarian Darmanitan (Zen Mode)","evolved":true,"galarian":true},
{"dex":556,"name":"Maracamba","en":"Maractus","regional":true},
{"dex":557,"name":"Lithomith","en":"Dwebble","getshiny":true},
{"dex":558,"name":"Castellith","en":"Crustle","evolved":true},
{"dex":559,"name":"Zurrokex","en":"Scraggy","getshiny":true},
{"dex":560,"name":"Irokex","en":"Scrafty","evolved":true},
{"dex":561,"name":"Symvolara","en":"Sigilyph","regional":true},
{"dex":562,"name":"Makabaja","en":"Yamask","getshiny":true},
{"dex":"562G","name":"Galar-Makabaja","en":"Galarian Yamask","galarian":true,"getshiny":true},
{"dex":563,"name":"Echnatoll","en":"Cofagrigus","evolved":true},
{"dex":564,"name":"Galapaflos","en":"Tirtouga","getshiny":true},
{"dex":565,"name":"Karippas","en":"Carracosta","evolved":true},
{"dex":566,"name":"Flapteryx","en":"Archen","getshiny":true},
{"dex":567,"name":"Aeropteryx","en":"Archeops","evolved":true},
{"dex":568,"name":"Unratütox","en":"Trubbish","getshiny":true},
{"dex":569,"name":"Deponitox","en":"Garbodor","evolved":true},
{"dex":570,"name":"Zorua"},
{"dex":"570H","name":"Hisui-Zorua","en":"Hisuian Zorua","hisuian":true},
{"dex":571,"name":"Zoroark","evolved":true},
{"dex":"571H","name":"Hisui-Zoroark","en":"Hisuian Zoroark","hisuian":true,"evolved":true},
{"dex":572,"name":"Picochilla","en":"Minccino","getshiny":true},
{"dex":573,"name":"Chillabell","en":"Cinccino","evolved":true},
{"dex":574,"name":"Mollimorba","en":"Gothita"},
{"dex":575,"name":"Hypnomorba","en":"Gothorita","evolved":true},
{"dex":576,"name":"Morbitesse","en":"Gothitelle","evolved":true},
{"dex":577,"name":"Monozyto","en":"Solosis"},
{"dex":578,"name":"Mitodos","en":"Duosion","evolved":true},
{"dex":579,"name":"Zytomega","en":"Reuniclus","evolved":true},
{"dex":580,"name":"Piccolente","en":"Ducklett"},
{"dex":581,"name":"Swaroness","en":"Swanna","evolved":true},
{"dex":582,"name":"Gelatini","en":"Vanillite"},
{"dex":583,"name":"Gelatroppo","en":"Vanillish","evolved":true},
{"dex":584,"name":"Gelatwino","en":"Vanilluxe","evolved":true},
{"dex":585,"name":"Sesokitz (Frühling)","de":"Sesokitz (Frühlingsform)","en":"Deerling (Spring Form)"},
{"dex":"585S","name":"Sesokitz (Sommer)","de":"Sesokitz (Sommerform)","en":"Deerling (Summer Form)"},
{"dex":"585A","name":"Sesokitz (Herbst)","de":"Sesokitz (Herbstform)","en":"Deerling (Autumn Form)"},
{"dex":"585W","name":"Sesokitz (Winter)","de":"Sesokitz (Winterform)","en":"Deerling (Winter Form)"},
{"dex":586,"name":"Kronjuwild (Frühling)","de":"Kronjuwild (Frühlingsform)","en":"Sawsbuck (Spring Form)","evolved":true},
{"dex":"586S","name":"Kronjuwild (Sommer)","de":"Kronjuwild (Sommerform)","en":"Sawsbuck (Summer Form)","evolved":true},
{"dex":"586A","name":"Kronjuwild (Herbst)","de":"Kronjuwild (Herbstform)","en":"Sawsbuck (Autumn Form)","evolved":true},
{"dex":"586W","name":"Kronjuwild (Winter)","de":"Kronjuwild (Winterform)","en":"Sawsbuck (Winter Form)","evolved":true},
{"dex":587,"name":"Emolga"},
{"dex":588,"name":"Laukaps","en":"Karrablast","getshiny":true},
{"dex":589,"name":"Cavalanzas","en":"Escavalier","evolved":true},
{"dex":590,"name":"Tarnpignon","en":"Foongus","getshiny":true},
{"dex":591,"name":"Hutsassa","en":"Amoonguss","evolved":true},
{"dex":592,"name":"Quabbel","en":"Frillish","getshiny":true},
{"dex":593,"name":"Apoquallyp","en":"Jellicent","evolved":true},
{"dex":594,"name":"Mamolida","en":"Alomomola","getshiny":true},
{"dex":595,"name":"Wattzapf","en":"Joltik","getshiny":true},
{"dex":596,"name":"Voltula","en":"Galvantula","evolved":true},
{"dex":597,"name":"Kastadur","en":"Ferroseed","getshiny":true},
{"dex":598,"name":"Tentantel","en":"Ferrothorn","evolved":true},
{"dex":599,"name":"Klikk","en":"Klink","getshiny":true},
{"dex":600,"name":"Kliklak","en":"Klang","evolved":true},
{"dex":601,"name":"Klikdiklak","en":"Klinklang","evolved":true},
{"dex":602,"name":"Zapplardin","en":"Tynamo"},
{"dex":603,"name":"Zapplalek","en":"Eelektrik","evolved":true},
{"dex":604,"name":"Zapplarang","en":"Eelektross","evolved":true},
{"dex":605,"name":"Pygraulon","en":"Elgyem","getshiny":true},
{"dex":606,"name":"Megalon","en":"Beheeyem","evolved":true},
{"dex":607,"name":"Lichtel","en":"Litwick","getshiny":true},
{"dex":608,"name":"Laternecto","en":"Lampent","evolved":true},
{"dex":609,"name":"Skelabra","en":"Chandelure","evolved":true},
{"dex":610,"name":"Milza","en":"Axew","getshiny":true},
{"dex":611,"name":"Sharfax","en":"Fraxure","evolved":true},
{"dex":612,"name":"Maxax","en":"Haxorus","evolved":true},
{"dex":613,"name":"Petznief","en":"Cubchoo","getshiny":true},
{"dex":614,"name":"Siberio","en":"Beartic","evolved":true},
{"dex":615,"name":"Frigometri","en":"Cryogonal"},
{"dex":616,"name":"Schnuthelm","en":"Shelmet","getshiny":true},
{"dex":617,"name":"Hydragil","en":"Accelgor","evolved":true},
{"dex":618,"name":"Flunschlik","en":"Stunfisk","getshiny":true},
{"dex":"618G","name":"Galar-Flunschlik","en":"Galarian Stunfisk","galarian":true,"getshiny":true},
{"dex":619,"name":"Lin-Fu","en":"Mienfoo"},
{"dex":620,"name":"Wie-Shu","en":"Mienshao","evolved":true},
{"dex":621,"name":"Shardrago","en":"Druddigon","getshiny":true},
{"dex":622,"name":"Golbit","en":"Golett","getshiny":true},
{"dex":623,"name":"Golgantes","en":"Golurk","evolved":true},
{"dex":624,"name":"Gladiantri","en":"Pawniard","getshiny":true},
{"dex":625,"name":"Caesurio","en":"Bisharp","evolved":true},
{"dex":626,"name":"Bisofank","en":"Bouffalant","regional":true},
{"dex":627,"name":"Geronimatz","en":"Rufflet","getshiny":true},
{"dex":628,"name":"Washakwil","en":"Braviary","evolved":true},
{"dex":"628H","name":"Hisui-Washakwil","en":"Hisuian Braviary","evolved":true,"hisuian":true,"getshiny":true},
{"dex":629,"name":"Skallyk","en":"Vullaby","getshiny":true},
{"dex":630,"name":"Grypheldis","en":"Mandibuzz","evolved":true},
{"dex":631,"name":"Furnifraß","en":"Heatmor","regional":true,"getshiny":true},
{"dex":632,"name":"Fermicula","en":"Durant","regional":true,"getshiny":true},
{"dex":633,"name":"Kapuno","en":"Deino","getshiny":true},
{"dex":634,"name":"Duodino","en":"Zweilous","evolved":true},
{"dex":635,"name":"Trikephalo","en":"Hydreigon","evolved":true},
{"dex":636,"name":"Ignivor","en":"Larvesta"},
{"dex":637,"name":"Ramoth","en":"Volcarona","evolved":true},
{"dex":638,"name":"Kobalium","en":"Cobalion","legendary":true,"getshiny":true},
{"dex":639,"name":"Terrakium","en":"Terrakion","legendary":true,"getshiny":true},
{"dex":640,"name":"Viridium","en":"Virizion","legendary":true,"getshiny":true},
{"dex":641,"name":"Boreos (Inkarnation)","de":"Boreos (Inkarnationsform)","en":"Tornadus (Incarnate Forme)","legendary":true,"getshiny":true},
{"dex":"641T","name":"Boreos (Tiergeist)","de":"Boreos (Tiergeistform)","en":"Tornadus (Therian Forme)","legendary":true,"getshiny":true},
{"dex":642,"name":"Voltolos (Inkarnation)","de":"Voltolos (Inkarnationsform)","en":"Thundurus (Incarnate Forme)","legendary":true,"getshiny":true},
{"dex":"642T","name":"Voltolos (Tiergeist)","de":"Voltolos (Tiergeistform)","en":"Thundurus (Therian Forme)","legendary":true,"getshiny":true},
{"dex":643,"name":"Reshiram","legendary":true,"getshiny":true},
{"dex":644,"name":"Zekrom","legendary":true,"getshiny":true},
{"dex":645,"name":"Demeteros (Inkarnation)","de":"Demeteros (Inkarnationsform)","en":"Landorus (Incarnate Forme)","legendary":true,"getshiny":true},
{"dex":"645T","name":"Demeteros (Tiergeist)","de":"Demeteros (Tiergeistform)","en":"Landorus (Therian Forme)","legendary":true,"getshiny":true},
{"dex":646,"name":"Kyurem","legendary":true,"getshiny":true},
{"dex":"646B","name":"Schwarzes Kyurem","de":"Schwarzes Kyurem","en":"Black Kyurem","legendary":true},
{"dex":"646W","name":"Weißes Kyurem","de":"Weißes Kyurem","en":"White Kyurem","legendary":true},
{"dex":647,"name":"Keldeo (Standard)","de":"Keldeo (Standardform)","en":"Keldeo (Ordinary Form)","mythical":true},
{"dex":"647R","name":"Keldeo (Resolut)","de":"Keldeo (Resolutform)","en":"Keldeo (Resolute Form)","mythical":true},
{"dex":648,"name":"Meloetta (Gesang)","de":"Meloetta (Gesangsform)","en":"Meloetta (Aria Forme)","mythical":true},
{"dex":"648P","name":"Meloetta (Tanz)","de":"Meloetta (Tanzform)","en":"Meloetta (Pirouette Forme)","mythical":true},
{"dex":649,"name":"Genesect","mythical":true,"getshiny":true},
{"dex":"649B","name":"Genesect (Flammenmodul)","de":"Genesect mit Flammenmodul","en":"Genesect with Burn Drive","mythical":true},
{"dex":"649C","name":"Genesect (Eismodul)","de":"Genesect mit Gefriermodul","en":"Genesect with Chill Drive","mythical":true},
{"dex":"649D","name":"Genesect (Aquamodul)","de":"Genesect mit Aquamodul","en":"Genesect with Douse Drive","mythical":true},
{"dex":"649S","name":"Genesect (Blitzmodul)","de":"Genesect mit Blitzmodul","en":"Genesect with Shock Drive","mythical":true,"getshiny":true},
{"dex":650,"name":"Igamaro","en":"Chespin","getshiny":true},
{"dex":651,"name":"Igastarnish","en":"Quilladin","evolved":true},
{"dex":652,"name":"Brigaron","en":"Chesnaught","evolved":true},
{"dex":653,"name":"Fynx","en":"Fennekin","getshiny":true},
{"dex":654,"name":"Rutena","en":"Braixen","evolved":true},
{"dex":655,"name":"Fennexis","en":"Delphox","evolved":true},
{"dex":656,"name":"Froxy","en":"Froakie","getshiny":true},
{"dex":657,"name":"Amphizel","en":"Frogadier","evolved":true},
{"dex":658,"name":"Quajutsu","en":"Greninja","evolved":true},
{"dex":"658A","name":"Ash-Quajutsu","en":"Ash-Greninja","evolved":true},
{"dex":659,"name":"Scoppel","en":"Bunnelby","getshiny":true},
{"dex":660,"name":"Grebbit","en":"Diggersby","evolved":true},
{"dex":661,"name":"Dartiri","en":"Fletchling","getshiny":true},
{"dex":662,"name":"Dartignis","en":"Fletchinder","evolved":true},
{"dex":663,"name":"Fiaro","en":"Talonflame","evolved":true},
{"dex":664,"name":"Purmel","en":"Scatterbug"},
{"dex":665,"name":"Puponcho","en":"Spewpa","evolved":true},
{"dex":666,"name":"Vivillon","evolved":true},
{"dex":667,"name":"Leufeo","en":"Litleo","getshiny":true},
{"dex":668,"name":"Pyroleo","en":"Pyroar","evolved":true},
{"dex":669,"name":"Flabébé"},
{"dex":670,"name":"Floette","evolved":true},
{"dex":"670E","name":"Floette (Ewigblütler)","en":"Floette (Eternal Flower)","legendary":true},
{"dex":671,"name":"Florges","evolved":true},
{"dex":672,"name":"Mähikel","en":"Skiddo"},
{"dex":673,"name":"Chevrumm","en":"Gogoat","evolved":true},
{"dex":674,"name":"Pam-Pam","en":"Pancham","getshiny":true},
{"dex":675,"name":"Pandagro","en":"Pangoro","evolved":true},
{"dex":676,"name":"Coiffwaff","en":"Furfrou","getshiny":true},
{"dex":677,"name":"Psiau","en":"Espurr","getshiny":true},
{"dex":678,"name":"Psiaugon","en":"Meowstic","evolved":true},
{"dex":679,"name":"Gramokles","en":"Honedge"},
{"dex":680,"name":"Duokles","en":"Doublade","evolved":true},
{"dex":681,"name":"Durengard (Schild)","de":"Durengard (Schildform)","en":"Aegislash (Shield Forme)","evolved":true},
{"dex":"681B","name":"Durengard (Klinge)","de":"Durengard (Klingenform)","en":"Aegislash (Blade Forme)","evolved":true},
{"dex":682,"name":"Parfi","en":"Spritzee","getshiny":true},
{"dex":683,"name":"Parfinesse","en":"Aromatisse","evolved":true},
{"dex":684,"name":"Flauschling","en":"Swirlix","getshiny":true},
{"dex":685,"name":"Sabbaione","en":"Slurpuff","evolved":true},
{"dex":686,"name":"Iscalar","en":"Inkay","getshiny":true},
{"dex":687,"name":"Calamanero","en":"Malamar","evolved":true},
{"dex":688,"name":"Bithora","en":"Binacle","getshiny":true},
{"dex":689,"name":"Thanathora","en":"Barbaracle","evolved":true},
{"dex":690,"name":"Algitt","en":"Skrelp","getshiny":true},
{"dex":691,"name":"Tandrak","en":"Dragalge","evolved":true},
{"dex":692,"name":"Scampisto","en":"Clauncher","getshiny":true},
{"dex":693,"name":"Wummer","en":"Clawitzer","evolved":true},
{"dex":694,"name":"Eguana","en":"Helioptile","getshiny":true},
{"dex":695,"name":"Elezard","en":"Heliolisk","evolved":true},
{"dex":696,"name":"Balgoras","en":"Tyrunt","getshiny":true},
{"dex":697,"name":"Monargoras","en":"Tyrantrum","evolved":true},
{"dex":698,"name":"Amarino","en":"Amaura","getshiny":true},
{"dex":699,"name":"Amagarga","en":"Aurorus","evolved":true},
{"dex":700,"name":"Feelinara","en":"Sylveon","evolved":true},
{"dex":701,"name":"Resladero","en":"Hawlucha","regional":true},
{"dex":702,"name":"Dedenne","getshiny":true},
{"dex":703,"name":"Rocara","en":"Carbink"},
{"dex":704,"name":"Viscora","en":"Goomy","getshiny":true},
{"dex":705,"name":"Viscargot","en":"Sliggoo","evolved":true},
{"dex":"705H","name":"Hisui-Viscargot","en":"Hisuian Sliggoo","hisuian":true,"evolved":true},
{"dex":706,"name":"Viscogon","en":"Goodra","evolved":true},
{"dex":"706H","name":"Hisui-Viscogon","en":"Hisuian Goodra","hisuian":true,"evolved":true},
{"dex":707,"name":"Clavion","en":"Klefki","regional":true},
{"dex":708,"name":"Paragoni","en":"Phantump"},
{"dex":709,"name":"Trombork","en":"Trevenant","evolved":true},
{"dex":710,"name":"Irrbis (M)","de":"Irrbis (Größe M)","en":"Pumpkaboo (Average Size)","getshiny":true},
{"dex":"710S","name":"Irrbis (S)","de":"Irrbis (Größe S)","en":"Pumpkaboo (Small Size)","getshiny":true},
{"dex":"710L","name":"Irrbis (L)","de":"Irrbis (Größe L)","en":"Pumpkaboo (Large Size)","getshiny":true},
{"dex":"710X","name":"Irrbis (XL)","de":"Irrbis (Größe XL)","en":"Pumpkaboo (Super Size)","getshiny":true},
{"dex":711,"name":"Pumpdjinn (M)","de":"Pumpdjinn (Größe M)","en":"Gourgeist (Average Size)","evolved":true},
{"dex":"711S","name":"Pumpdjinn (S)","de":"Pumpdjinn (Größe S)","en":"Gourgeist (Small Size)","evolved":true},
{"dex":"711L","name":"Pumpdjinn (L)","de":"Pumpdjinn (Größe L)","en":"Gourgeist (Large Size)","evolved":true},
{"dex":"711X","name":"Pumpdjinn (XL)","de":"Pumpdjinn (Größe XL)","en":"Gourgeist (Super Size)","evolved":true},
{"dex":712,"name":"Arktip","en":"Bergmite","getshiny":true},
{"dex":713,"name":"Arktilas","en":"Avalugg","evolved":true},
{"dex":"713H","name":"Hisui-Arktilas","en":"Hisuian Avalugg","hisuian":true,"evolved":true,"getshiny":true},
{"dex":714,"name":"eF-eM","en":"Noibat","getshiny":true},
{"dex":715,"name":"UHaFnir","en":"Noivern","evolved":true},
{"dex":716,"name":"Xerneas","legendary":true,"getshiny":true},
{"dex":717,"name":"Yveltal","legendary":true,"getshiny":true},
{"dex":718,"name":"Zygarde","de":"50%-Zygarde","en":"Zygarde 50% Forme","legendary":true},
{"dex":"718T","name":"Zygarde (10%)","de":"10%-Zygarde","en":"Zygarde 10% Forme","legendary":true},
{"dex":"718C","name":"Zygarde (Optimum)","de":"Optimum-Zygarde","en":"Zygarde Complete Forme","legendary":true},
{"dex":719,"name":"Diancie","mythical":true},
{"dex":720,"name":"Hoopa (Gebannt)","de":"Gebanntes Hoopa","en":"Hoopa Confined","mythical":true},
{"dex":"720U","name":"Hoopa (Entfesselt)","de":"Entfesseltes Hoopa","en":"Hoopa Unbound","mythical":true},
{"dex":721,"name":"Volcanion","mythical":true},
{"dex":"3M","name":"Mega-Bisaflor","en":"Mega Venusaur","evolved":true,"mega":true},
{"dex":"6X","name":"Mega-Glurak X","en":"Mega Charizard X","evolved":true,"mega":true},
{"dex":"6Y","name":"Mega-Glurak Y","en":"Mega Charizard Y","evolved":true,"mega":true},
{"dex":"9M","name":"Mega-Turtok","en":"Mega Blastoise","evolved":true,"mega":true},
{"dex":"15M","name":"Mega-Bibor","en":"Mega Beedrill","evolved":true,"mega":true},
{"dex":"18M","name":"Mega-Tauboss","en":"Mega Pidgeot","evolved":true,"mega":true},
{"dex":"65M","name":"Mega-Simsala","en":"Mega Alakazam","evolved":true,"mega":true},
{"dex":"80M","name":"Mega-Lahmus","en":"Mega Slowbro","evolved":true,"mega":true},
{"dex":"94M","name":"Mega-Gengar","en":"Mega Gengar","evolved":true,"mega":true},
{"dex":"115M","name":"Mega-Kangama","en":"Mega Kangaskhan","mega":true},
{"dex":"127M","name":"Mega-Pinsir","en":"Mega Pinsir","mega":true},
{"dex":"130M","name":"Mega-Garados","en":"Mega Gyarados","evolved":true,"mega":true},
{"dex":"142M","name":"Mega-Aerodactyl","en":"Mega Aerodactyl","mega":true},
{"dex":"150X","name":"Mega-Mewtu X","en":"Mega Mewtwo X","mega":true},
{"dex":"150Y","name":"Mega-Mewtu Y","en":"Mega Mewtwo Y","mega":true},
{"dex":"181M","name":"Mega-Ampharos","en":"Mega Ampharos","evolved":true,"mega":true},
{"dex":"208M","name":"Mega-Stahlos","en":"Mega Steelix","evolved":true,"mega":true},
{"dex":"212M","name":"Mega-Scherox","en":"Mega Scizor","evolved":true,"mega":true},
{"dex":"214M","name":"Mega-Skaraborn","en":"Mega Heracross","evolved":true,"mega":true},
{"dex":"229M","name":"Mega-Hundemon","en":"Mega Houndoom","evolved":true,"mega":true},
{"dex":"248M","name":"Mega-Despotar","en":"Mega Tyranitar","evolved":true,"mega":true},
{"dex":"254M","name":"Mega-Gewaldro","en":"Mega Sceptile","evolved":true,"mega":true},
{"dex":"257M","name":"Mega-Lohgock","en":"Mega Blaziken","evolved":true,"mega":true},
{"dex":"260M","name":"Mega-Sumpex","en":"Mega Swampert","evolved":true,"mega":true},
{"dex":"282M","name":"Mega-Guardevoir","en":"Mega Gardevoir","evolved":true,"mega":true},
{"dex":"302M","name":"Mega-Zobiris","en":"Mega Sableye","mega":true},
{"dex":"303M","name":"Mega-Flunkifer","en":"Mega Mawile","mega":true},
{"dex":"306M","name":"Mega-Stolloss","en":"Mega Aggron","evolved":true,"mega":true},
{"dex":"308M","name":"Mega-Meditalis","en":"Mega Medicham","evolved":true,"mega":true},
{"dex":"310M","name":"Mega-Voltenso","en":"Mega Manectric","evolved":true,"mega":true},
{"dex":"319M","name":"Mega-Tohaido","en":"Mega Sharpedo","evolved":true,"mega":true},
{"dex":"323M","name":"Mega-Camerupt","en":"Mega Camerupt","evolved":true,"mega":true},
{"dex":"334M","name":"Mega-Altaria","en":"Mega Altaria","evolved":true,"mega":true},
{"dex":"354M","name":"Mega-Banette","en":"Mega Banette","evolved":true,"mega":true},
{"dex":"359M","name":"Mega-Absol","en":"Mega Absol","mega":true},
{"dex":"362M","name":"Mega-Firnontor","en":"Mega Glalie","evolved":true,"mega":true},
{"dex":"373M","name":"Mega-Brutalanda","en":"Mega Salamence","evolved":true,"mega":true},
{"dex":"376M","name":"Mega-Metagross","en":"Mega Metagross","evolved":true,"mega":true},
{"dex":"380M","name":"Mega-Latias","en":"Mega Latias","legendary":true,"mega":true},
{"dex":"381M","name":"Mega-Latios","en":"Mega Latios","legendary":true,"mega":true},
{"dex":"382P","name":"Proto-Kyogre","en":"Primal Kyogre","legendary":true,"mega":true},
{"dex":"383P","name":"Proto-Groudon","en":"Primal Groudon","legendary":true,"mega":true},
{"dex":"384M","name":"Mega-Rayquaza","en":"Mega Rayquaza","legendary":true,"mega":true},
{"dex":"428M","name":"Mega-Schlapor","en":"Mega Lopunny","evolved":true,"mega":true},
{"dex":"445M","name":"Mega-Knakrack","en":"Mega Garchomp","evolved":true,"mega":true},
{"dex":"448M","name":"Mega-Lucario","en":"Mega Lucario","evolved":true,"mega":true},
{"dex":"460M","name":"Mega-Rexblisar","en":"Mega Abomasnow","evolved":true,"mega":true},
{"dex":"475M","name":"Mega-Galagladi","en":"Mega Gallade","evolved":true,"mega":true},
{"dex":"531M","name":"Mega-Ohrdoch","en":"Mega Audino","mega":true},
{"dex":"719M","name":"Mega-Diancie","en":"Mega Diancie","mythical":true,"mega":true},
{"dex":722,"name":"Bauz","en":"Rowlet"},
{"dex":723,"name":"Arboretoss","en":"Dartrix","evolved":true},
{"dex":724,"name":"Silvarro","en":"Decidueye","evolved":true},
{"dex":"724H","name":"Hisui-Silvarro","en":"Hisuian Decidueye","hisuian":true,"evolved":true},
{"dex":725,"name":"Flamiau","en":"Litten"},
{"dex":726,"name":"Miezunder","en":"Torracat","evolved":true},
{"dex":727,"name":"Fuegro","en":"Incineroar","evolved":true},
{"dex":728,"name":"Robball","en":"Popplio"},
{"dex":729,"name":"Marikeck","en":"Brionne","evolved":true},
{"dex":730,"name":"Primarene","en":"Primarina","evolved":true},
{"dex":731,"name":"Peppeck","en":"Pikipek"},
{"dex":732,"name":"Trompeck","en":"Trumbeak","evolved":true},
{"dex":733,"name":"Tukanon","en":"Toucannon","evolved":true},
{"dex":734,"name":"Mangunior","en":"Yungoos","getshiny":true},
{"dex":735,"name":"Manguspektor","en":"Gumshoos","evolved":true},
{"dex":736,"name":"Mabula","en":"Grubbin"},
{"dex":737,"name":"Akkup","en":"Charjabug","evolved":true},
{"dex":738,"name":"Donarion","en":"Vikavolt","evolved":true},
{"dex":739,"name":"Krabbox","en":"Crabrawler"},
{"dex":740,"name":"Krawell","en":"Crabominable","evolved":true},
{"dex":741,"name":"Choreogel (Flamenco)","de":"Choreogel (Flamenco-Stil)","en":"Oricorio (Baile Style)","regional":true},
{"dex":"741M","name":"Choreogel (Cheerleading)","de":"Choreogel (Cheerleading-Stil)","en":"Oricorio (Pom-Pom Style)","regional":true},
{"dex":"741P","name":"Choreogel (Hula)","de":"Choreogel (Hula-Stil)","en":"Oricorio (Pa'u Style)","regional":true},
{"dex":"741S","name":"Choreogel (Buyo)","de":"Choreogel (Buyo-Stil)","en":"Oricorio (Sensu Style)","regional":true},
{"dex":742,"name":"Wommel","en":"Cutiefly"},
{"dex":743,"name":"Bandelby","en":"Ribombee","evolved":true},
{"dex":744,"name":"Wuffels","en":"Rockruff","getshiny":true},
{"dex":745,"name":"Wolwerock (Tag)","de":"Wolwerock (Tagform)","en":"Lycanroc (Midday Form)","evolved":true},
{"dex":"745N","name":"Wolwerock (Nacht)","de":"Wolwerock (Nachtform)","en":"Lycanroc (Midnight Form)","evolved":true},
{"dex":"745D","name":"Wolwerock (Zwielicht)","de":"Wolwerock (Zwielichtform)","en":"Lycanroc (Dusk Form)","evolved":true},
{"dex":746,"name":"Lusardin (Einzel)","de":"Lusardin (Einzelform)","en":"Wishiwashi (Solo Form)"},
{"dex":"746S","name":"Lusardin (Schwarm)","de":"Lusardin (Schwarmform)","en":"Wishiwashi (School Form)"},
{"dex":747,"name":"Garstella","en":"Mareanie"},
{"dex":748,"name":"Aggrostella","en":"Toxapex","evolved":true},
{"dex":749,"name":"Pampuli","en":"Mudbray"},
{"dex":750,"name":"Pampross","en":"Mudsdale","evolved":true},
{"dex":751,"name":"Araqua","en":"Dewpider","getshiny":true},
{"dex":752,"name":"Aranestro","en":"Araquanid","evolved":true},
{"dex":753,"name":"Imantis","en":"Fomantis","getshiny":true},
{"dex":754,"name":"Mantidea","en":"Lurantis","evolved":true},
{"dex":755,"name":"Bubungus","en":"Morelull"},
{"dex":756,"name":"Lamellux","en":"Shiinotic","evolved":true},
{"dex":757,"name":"Molunk","en":"Salandit"},
{"dex":758,"name":"Amfira","en":"Salazzle","evolved":true},
{"dex":759,"name":"Velursi","en":"Stufful","getshiny":true},
{"dex":760,"name":"Kosturso","en":"Bewear","evolved":true},
{"dex":761,"name":"Frubberl","en":"Bounsweet"},
{"dex":762,"name":"Frubaila","en":"Steenee","evolved":true},
{"dex":763,"name":"Fruyal","en":"Tsareena","evolved":true},
{"dex":764,"name":"Curelei","en":"Comfey","regional":true},
{"dex":765,"name":"Kommandutan","en":"Oranguru","getshiny":true},
{"dex":766,"name":"Quartermak","en":"Passimian"},
{"dex":767,"name":"Reißlaus","en":"Wimpod"},
{"dex":768,"name":"Tectass","en":"Golisopod","evolved":true},
{"dex":769,"name":"Sankabuh","en":"Sandygast"},
{"dex":770,"name":"Colossand","en":"Palossand","evolved":true},
{"dex":771,"name":"Gufa","en":"Pyukumuku"},
{"dex":772,"name":"Typ:Null","en":"Type: Null","legendary":true},
{"dex":773,"name":"Amigento","en":"Silvally","legendary":true,"evolved":true},
{"dex":774,"name":"Meteno (Meteor)","de":"Meteno (Meteorform)","en":"Minior (Meteor Form)"},
{"dex":"774C","name":"Meteno (Kern)","en":"Minior (Core)"},
{"dex":775,"name":"Koalelu","en":"Komala"},
{"dex":776,"name":"Tortunator","en":"Turtonator","getshiny":true},
{"dex":777,"name":"Togedemaru"},
{"dex":778,"name":"Mimigma","en":"Mimikyu"},
{"dex":779,"name":"Knirfish","en":"Bruxish"},
{"dex":780,"name":"Sen-Long","en":"Drampa"},
{"dex":781,"name":"Moruda","en":"Dhelmise"},
{"dex":782,"name":"Miniras","en":"Jangmo-o"},
{"dex":783,"name":"Mediras","en":"Hakamo-o","evolved":true},
{"dex":784,"name":"Grandiras","en":"Kommo-o","evolved":true},
{"dex":785,"name":"Kapu-Riki","en":"Tapu Koko","legendary":true,"getshiny":true},
{"dex":786,"name":"Kapu-Fala","en":"Tapu Lele","legendary":true,"getshiny":true},
{"dex":787,"name":"Kapu-Toro","en":"Tapu Bulu","legendary":true,"getshiny":true},
{"dex":788,"name":"Kapu-Kime","en":"Tapu Fini","legendary":true,"getshiny":true},
{"dex":789,"name":"Cosmog","legendary":true},
{"dex":790,"name":"Cosmovum","en":"Cosmoem","legendary":true,"evolved":true},
{"dex":791,"name":"Solgaleo","legendary":true,"evolved":true},
{"dex":792,"name":"Lunala","legendary":true,"evolved":true},
{"dex":793,"name":"Anego","en":"Nihilego","ultrabeast":true,"getshiny":true},
{"dex":794,"name":"Masskito","en":"Buzzwole","ultrabeast":true},
{"dex":795,"name":"Schabelle","en":"Pheromosa","ultrabeast":true},
{"dex":796,"name":"Voltriant","en":"Xurkitree","ultrabeast":true},
{"dex":797,"name":"Kaguron","en":"Celesteela","ultrabeast":true,"regional":true},
{"dex":798,"name":"Katagami","en":"Kartana","ultrabeast":true,"regional":true},
{"dex":799,"name":"Schlingking","en":"Guzzlord","ultrabeast":true},
{"dex":800,"name":"Necrozma","legendary":true},
{"dex":"800M","name":"Necrozma (Abendmähne)","en":"Dusk Mane Necrozma","legendary":true},
{"dex":"800W","name":"Necrozma (Morgenschwingen)","en":"Dawn Wings Necrozma","legendary":true},
{"dex":"800U","name":"Ultra-Necrozma","en":"Ultra Necrozma","legendary":true},
{"dex":801,"name":"Magearna","mythical":true},
{"dex":802,"name":"Marshadow","mythical":true},
{"dex":803,"name":"Venicro","en":"Poipole","ultrabeast":true},
{"dex":804,"name":"Agoyon","en":"Naganadel","ultrabeast":true,"evolved":true},
{"dex":805,"name":"Muramura","en":"Stakataka","ultrabeast":true},
{"dex":806,"name":"Kopplosio","en":"Blacephalon","ultrabeast":true},
{"dex":807,"name":"Zeraora","mythical":true},
{"dex":808,"name":"Meltan","mythical":true},
{"dex":809,"name":"Melmetal","mythical":true,"evolved":true},
{"dex":810,"name":"Chimpep","en":"Grookey"},
{"dex":811,"name":"Chimstix","en":"Thwackey","evolved":true},
{"dex":812,"name":"Gortrom","en":"Rillaboom","evolved":true},
{"dex":813,"name":"Hopplo","en":"Scorbunny"},
{"dex":814,"name":"Kickerlo","en":"Raboot","evolved":true},
{"dex":815,"name":"Liberlo","en":"Cinderace","evolved":true},
{"dex":816,"name":"Memmeon","en":"Sobble"},
{"dex":817,"name":"Phlegleon","en":"Drizzile","evolved":true},
{"dex":818,"name":"Intelleon","en":"Inteleon","evolved":true},
{"dex":819,"name":"Raffel","en":"Skwovet"},
{"dex":820,"name":"Schlaraffel","en":"Greedent","evolved":true},
{"dex":821,"name":"Meikro","en":"Rookidee"},
{"dex":822,"name":"Kranoviz","en":"Corvisquire","evolved":true},
{"dex":823,"name":"Krarmor","en":"Corviknight","evolved":true},
{"dex":824,"name":"Sensect","en":"Blipbug"},
{"dex":825,"name":"Keradar","en":"Dottler","evolved":true},
{"dex":826,"name":"Maritellit","en":"Orbeetle","evolved":true},
{"dex":827,"name":"Kleptifux","en":"Nickit"},
{"dex":828,"name":"Gaunux","en":"Thievul","evolved":true},
{"dex":829,"name":"Cottini","en":"Gossifleur"},
{"dex":830,"name":"Cottomi","en":"Eldegoss","evolved":true},
{"dex":831,"name":"Wolly","en":"Wooloo"},
{"dex":832,"name":"Zwollock","en":"Dubwool","evolved":true},
{"dex":833,"name":"Kamehaps","en":"Chewtle"},
{"dex":834,"name":"Kamalm","en":"Drednaw","evolved":true},
{"dex":835,"name":"Voldi","en":"Yamper"},
{"dex":836,"name":"Bellektro","en":"Boltund","evolved":true},
{"dex":837,"name":"Klonkett","en":"Rolycoly"},
{"dex":838,"name":"Wagong","en":"Carkol","evolved":true},
{"dex":839,"name":"Montecarbo","en":"Coalossal","evolved":true},
{"dex":840,"name":"Knapfel","en":"Applin"},
{"dex":841,"name":"Drapfel","en":"Flapple","evolved":true},
{"dex":842,"name":"Schlapfel","en":"Appletun","evolved":true},
{"dex":843,"name":"Salanga","en":"Silicobra"},
{"dex":844,"name":"Sanaconda","en":"Sandaconda","evolved":true},
{"dex":845,"name":"Urgl","en":"Cramorant"},
{"dex":846,"name":"Pikuda","en":"Arrokuda"},
{"dex":847,"name":"Barrakiefa","en":"Barraskewda","evolved":true},
{"dex":848,"name":"Toxel"},
{"dex":849,"name":"Riffex","en":"Toxtricity","evolved":true},
{"dex":850,"name":"Thermopod","en":"Sizzlipede"},
{"dex":851,"name":"Infernopod","en":"Centiskorch","evolved":true},
{"dex":852,"name":"Klopptopus","en":"Clobbopus"},
{"dex":853,"name":"Kaocto","en":"Grapploct","evolved":true},
{"dex":854,"name":"Fatalitee","en":"Sinistea"},
{"dex":855,"name":"Mortipot","en":"Polteageist","evolved":true},
{"dex":856,"name":"Brimova","en":"Hatenna"},
{"dex":857,"name":"Brimano","en":"Hattrem","evolved":true},
{"dex":858,"name":"Silembrim","en":"Hatterene","evolved":true},
{"dex":859,"name":"Bähmon","en":"Impidimp"},
{"dex":860,"name":"Pelzebub","en":"Morgrem","evolved":true},
{"dex":861,"name":"Olangaar","en":"Grimmsnarl","evolved":true},
{"dex":862,"name":"Barrikadax","en":"Obstagoon","evolved":true},
{"dex":863,"name":"Mauzinger","en":"Perrserker","evolved":true},
{"dex":864,"name":"Gorgasonn","en":"Cursola","regional":true,"evolved":true},
{"dex":865,"name":"Lauchzelot","en":"Sirfetch'd","evolved":true},
{"dex":866,"name":"Pantifrost","en":"Mr. Rime","evolved":true},
{"dex":867,"name":"Oghnatoll","en":"Runerigus","evolved":true},
{"dex":868,"name":"Hokumil","en":"Milcery"},
{"dex":869,"name":"Pokusan","en":"Alcremie","evolved":true},
{"dex":870,"name":"Legios","en":"Falinks"},
{"dex":871,"name":"Britzigel","en":"Pincurchin"},
{"dex":872,"name":"Snomnom","en":"Snom"},
{"dex":873,"name":"Mottineva","en":"Frosmoth","evolved":true},
{"dex":874,"name":"Humanolith","en":"Stonjourner"},
{"dex":875,"name":"Kubuin (Tiefkühlkopf)","en":"Eiscue (Ice Face)"},
{"dex":"875N","name":"Kubuin (Wohlfühlkopf)","en":"Eiscue (Noice Face)"},
{"dex":876,"name":"Servol","en":"Indeedee"},
{"dex":877,"name":"Morpeko"},
{"dex":878,"name":"Kupfanti","en":"Cufant"},
{"dex":879,"name":"Patinaraja","en":"Copperajah","evolved":true},
{"dex":880,"name":"Lectragon","en":"Dracozolt"},
{"dex":881,"name":"Lecryodon","en":"Arctozolt"},
{"dex":882,"name":"Pescragon","en":"Dracovish"},
{"dex":883,"name":"Pescryodon","en":"Arctovish"},
{"dex":884,"name":"Duraludon"},
{"dex":885,"name":"Grolldra","en":"Dreepy"},
{"dex":886,"name":"Phandra","en":"Drakloak","evolved":true},
{"dex":887,"name":"Katapuldra","en":"Dragapult","evolved":true},
{"dex":888,"name":"Zacian (Krieger)","de":"Zacian (Heldenhafter Krieger)","en":"Zacian (Hero of Many Battles)","legendary":true},
{"dex":"888C","name":"Zacian (König)","de":"Zacian (König des Schwertes)","en":"Zacian (Crowned Sword)","legendary":true},
{"dex":889,"name":"Zamazenta (Krieger)","de":"Zamazenta (Heldenhafter Krieger)","en":"Zamazenta (Hero of Many Battles)","legendary":true},
{"dex":"889C","name":"Zamazenta (König)","de":"Zamazenta (König des Schildes)","en":"Zamazenta (Crowned Shield)","legendary":true},
{"dex":890,"name":"Endynalos","en":"Eternatus","legendary":true},
{"dex":891,"name":"Dakuma","en":"Kubfu","legendary":true},
{"dex":892,"name":"Wulaosu (Fokussierter Stil)","en":"Urshifu (Single Strike Style)","legendary":true,"evolved":true},
{"dex":"892R","name":"Wulaosu (Fließender Stil)","en":"Urshifu (Rapid Strike Style)","legendary":true,"evolved":true},
{"dex":893,"name":"Zarude","mythical":true},
{"dex":"893D","name":"Papa Zarude","en":"Dada Zarude","mythical":true},
{"dex":894,"name":"Regieleki","legendary":true},
{"dex":895,"name":"Regidrago","legendary":true},
{"dex":896,"name":"Polaross","en":"Glastrier","legendary":true},
{"dex":897,"name":"Phantoross","en":"Spectrier","legendary":true},
{"dex":898,"name":"Coronospa","en":"Calyrex","legendary":true},
{"dex":"898I","name":"Coronospa (Schimmelreiter)","en":"Calyrex (Ice Rider)","legendary":true},
{"dex":"898S","name":"Coronospa (Rappenreiter)","en":"Calyrex (Shadow Rider)","legendary":true},
{"dex":"6G","name":"Gigadynamax-Glurak","en":"Gigantamax Charizard","evolved":true,"gigantamax":true},
{"dex":"12G","name":"Gigadynamax-Smettbo","en":"Gigantamax Butterfree","evolved":true,"gigantamax":true},
{"dex":"25G","name":"Gigadynamax-Pikachu","en":"Gigantamax Pikachu","gigantamax":true},
{"dex":"52GM","name":"Gigadynamax-Mauzi","en":"Gigantamax Meowth","gigantamax":true},
{"dex":"68G","name":"Gigadynamax-Machomei","en":"Gigantamax Machamp","evolved":true,"gigantamax":true},
{"dex":"94G","name":"Gigadynamax-Gengar","en":"Gigantamax Gengar","evolved":true,"gigantamax":true},
{"dex":"99G","name":"Gigadynamax-Kingler","en":"Gigantamax Kingler","evolved":true,"gigantamax":true},
{"dex":"131G","name":"Gigadynamax-Lapras","en":"Gigantamax Lapras","gigantamax":true},
{"dex":"133G","name":"Gigadynamax-Evoli","en":"Gigantamax Eevee","gigantamax":true},
{"dex":"143G","name":"Gigadynamax-Relaxo","en":"Gigantamax Snorlax","gigantamax":true},
{"dex":"569G","name":"Gigadynamax-Deponitox","en":"Gigantamax Garbodor","evolved":true,"gigantamax":true},
{"dex":"809G","name":"Gigadynamax-Melmetal","en":"Gigantamax Melmetal","mythical":true,"evolved":true,"gigantamax":true},
{"dex":"823G","name":"Gigadynamax-Krarmor","en":"Gigantamax Corviknight","evolved":true,"gigantamax":true},
{"dex":"826G","name":"Gigadynamax-Maritellit","en":"Gigantamax Orbeetle","evolved":true,"gigantamax":true},
{"dex":"834G","name":"Gigadynamax-Kamalm","en":"Gigantamax Drednaw","evolved":true,"gigantamax":true},
{"dex":"839G","name":"Gigadynamax-Montecarbo","en":"Gigantamax Coalossal","evolved":true,"gigantamax":true},
{"dex":"841G","name":"Gigadynamax-Drapfel","en":"Gigantamax Flapple","evolved":true,"gigantamax":true},
{"dex":"842G","name":"Gigadynamax-Schlapfel","en":"Gigantamax Appletun","evolved":true,"gigantamax":true},
{"dex":"844G","name":"Gigadynamax-Sanaconda","en":"Gigantamax Sandaconda","evolved":true,"gigantamax":true},
{"dex":"849G","name":"Gigadynamax-Riffex","en":"Gigantamax Toxtricity","evolved":true,"gigantamax":true},
{"dex":"851G","name":"Gigadynamax-Infernopod","en":"Gigantamax Centiskorch","evolved":true,"gigantamax":true},
{"dex":"858G","name":"Gigadynamax-Silembrim","en":"Gigantamax Hatterene","evolved":true,"gigantamax":true},
{"dex":"861G","name":"Gigadynamax-Olangaar","en":"Gigantamax Grimmsnarl","evolved":true,"gigantamax":true},
{"dex":"869G","name":"Gigadynamax-Pokusan","en":"Gigantamax Alcremie","evolved":true,"gigantamax":true},
{"dex":"879G","name":"Gigadynamax-Patinaraja","en":"Gigantamax Copperajah","evolved":true,"gigantamax":true},
{"dex":"884G","name":"Gigadynamax-Duraludon","en":"Gigantamax Duraludon","gigantamax":true},
{"dex":"890E","name":"Unendynamax-Endynalos","en":"Eternamax Eternatus","legendary":true,"gigantamax":true},
{"dex":"892G","name":"Gigadynamax-Wulaosu (Fokussierter Stil)","en":"Gigantamax Urshifu (Single Strike Style)","legendary":true,"evolved":true,"gigantamax":true},
{"dex":"892RG","name":"Gigadynamax-Wulaosu (Fließender Stil)","en":"Gigantamax Urshifu (Rapid Strike Style)","legendary":true,"evolved":true,"gigantamax":true},
{"dex":899,"name":"Damythir","en":"Wyrdeer","evolved":true},
{"dex":900,"name":"Axantor","en":"Kleavor","evolved":true,"getshiny":true},
{"dex":901,"name":"Ursaluna","en":"Ursaluna","evolved":true},
{"dex":902,"name":"Salmagnis","en":"Basculegion","evolved":true},
{"dex":903,"name":"Snieboss","en":"Sneasler","evolved":true},
{"dex":904,"name":"Myriador","en":"Overqwil","evolved":true},
{"dex":905,"name":"Cupidos (Inkarnation)","de":"Cupidos (Inkarnationsform)","en":"Enamorus (Incarnate Forme)","legendary":true},
{"dex":"905T","name":"Cupidos (Tiergeist)","de":"Cupidos (Tiergeistform)","en":"Enamorus (Therian Forme)","legendary":true},
{"dex":906,"name":"Felori","en":"Sprigatito"},
{"dex":907,"name":"Feliospa","en":"Floragato","evolved":true},
{"dex":908,"name":"Maskagato","en":"Meowscarada","evolved":true},
{"dex":909,"name":"Krokel","en":"Fuecoco"},
{"dex":910,"name":"Lokroko","en":"Crocalor","evolved":true},
{"dex":911,"name":"Skelokrok","en":"Skeledirge","evolved":true},
{"dex":912,"name":"Kwaks","en":"Quaxly"},
{"dex":913,"name":"Fuentente","en":"Quaxwell","evolved":true},
{"dex":914,"name":"Bailonda","en":"Quaquaval","evolved":true},
{"dex":915,"name":"Ferkuli","en":"Lechonk","getshiny":true},
{"dex":916,"name":"Fragrunz","en":"Oinkologne","evolved":true},
{"dex":917,"name":"Tarundel","en":"Tarountula"},
{"dex":918,"name":"Spinsidias","en":"Spidops","evolved":true},
{"dex":919,"name":"Micrick","en":"Nymble"},
{"dex":920,"name":"Lextremo","en":"Lokix","evolved":true},
{"dex":921,"name":"Pamo","en":"Pawmi"},
{"dex":922,"name":"Pamamo","en":"Pawmo","evolved":true},
{"dex":923,"name":"Pamomamo","en":"Pawmot","evolved":true},
{"dex":924,"name":"Zwieps","en":"Tandemaus"},
{"dex":925,"name":"Famieps","en":"Maushold","evolved":true},
{"dex":926,"name":"Hefel","en":"Fidough"},
{"dex":927,"name":"Backel","en":"Dachsbun","evolved":true},
{"dex":928,"name":"Olini","en":"Smoliv"},
{"dex":929,"name":"Olivinio","en":"Dolliv","evolved":true},
{"dex":930,"name":"Olithena","en":"Arboliva","evolved":true},
{"dex":931,"name":"Krawalloro","en":"Squawkabilly"},
{"dex":932,"name":"Geosali","en":"Nacli"},
{"dex":933,"name":"Sedisal","en":"Naclstack","evolved":true},
{"dex":934,"name":"Saltigant","en":"Garganacl","evolved":true},
{"dex":935,"name":"Knarbon","en":"Charcadet"},
{"dex":936,"name":"Crimanzo","en":"Armarouge","evolved":true},
{"dex":937,"name":"Azugladis","en":"Ceruledge","evolved":true},
{"dex":938,"name":"Blipp","en":"Tadbulb"},
{"dex":939,"name":"Wampitz","en":"Bellibolt","evolved":true},
{"dex":940,"name":"Voltrel","en":"Wattrel"},
{"dex":941,"name":"Voltrean","en":"Kilowattrel","evolved":true},
{"dex":942,"name":"Mobtiff","en":"Maschiff"},
{"dex":943,"name":"Mastifioso","en":"Mabosstiff","evolved":true},
{"dex":944,"name":"Sproxi","en":"Shroodle"},
{"dex":945,"name":"Affiti","en":"Grafaiai","evolved":true},
{"dex":946,"name":"Weherba","en":"Bramblin"},
{"dex":947,"name":"Horrerba","en":"Brambleghast","evolved":true},
{"dex":948,"name":"Tentagra","en":"Toedscool"},
{"dex":949,"name":"Tenterra","en":"Toedscruel","evolved":true},
{"dex":950,"name":"Klibbe","en":"Klawf"},
{"dex":951,"name":"Chilingel","en":"Capsakid"},
{"dex":952,"name":"Halupenjo","en":"Scovillain","evolved":true},
{"dex":953,"name":"Relluk","en":"Rellor"},
{"dex":954,"name":"Skarabaks","en":"Rabsca","evolved":true},
{"dex":955,"name":"Flattutu","en":"Flittle"},
{"dex":956,"name":"Psiopatra","en":"Espathra","evolved":true},
{"dex":957,"name":"Forgita","en":"Tinkatink"},
{"dex":958,"name":"Tafforgita","en":"Tinkatuff","evolved":true},
{"dex":959,"name":"Granforgita","en":"Tinkaton","evolved":true},
{"dex":960,"name":"Schligda","en":"Wiglett"},
{"dex":961,"name":"Schligdri","en":"Wugtrio","evolved":true},
{"dex":962,"name":"Adebom","en":"Bombirdier"},
{"dex":963,"name":"Normifin","en":"Finizen"},
{"dex":964,"name":"Delfinator (Alltagsform)","en":"Palafin (Zero Form)","evolved":true},
{"dex":"964H","name":"Delfinator (Heldenform)","en":"Palafin (Hero Form)","evolved":true},
{"dex":965,"name":"Knattox","en":"Varoom"},
{"dex":966,"name":"Knattatox","en":"Revavroom","evolved":true},
{"dex":967,"name":"Mopex","en":"Cyclizar"},
{"dex":968,"name":"Schlurm","en":"Orthworm"},
{"dex":969,"name":"Lumispross","en":"Glimmet"},
{"dex":970,"name":"Lumiflora","en":"Glimmora","evolved":true},
{"dex":971,"name":"Gruff","en":"Greavard"},
{"dex":972,"name":"Friedwuff","en":"Houndstone","evolved":true},
{"dex":973,"name":"Flaminkno","en":"Flamigo"},
{"dex":974,"name":"Flaniwal","en":"Cetoddle"},
{"dex":975,"name":"Kolowal","en":"Cetitan","evolved":true},
{"dex":976,"name":"Agiluza","en":"Veluza"},
{"dex":977,"name":"Heerashai","en":"Dondozo"},
{"dex":978,"name":"Nigiragi","en":"Tatsugiri"},
{"dex":979,"name":"Epitaff","en":"Annihilape","evolved":true},
{"dex":980,"name":"Suelord","en":"Clodsire","evolved":true},
{"dex":981,"name":"Farigiraf","en":"Farigiraf","evolved":true},
{"dex":982,"name":"Dummimisel","en":"Dudunsparce","evolved":true},
{"dex":983,"name":"Gladimperio","en":"Kingambit","evolved":true},
{"dex":984,"name":"Riesenzahn","en":"Great Tusk","paradox":true},
{"dex":985,"name":"Brüllschweif","en":"Scream Tail","paradox":true},
{"dex":986,"name":"Wutpilz","en":"Brute Bonnet","paradox":true},
{"dex":987,"name":"Flatterhaar","en":"Flutter Mane","paradox":true},
{"dex":988,"name":"Kriechflügel","en":"Slither Wing","paradox":true},
{"dex":989,"name":"Sandfell","en":"Sandy Shocks","paradox":true},
{"dex":990,"name":"Eisenrad","en":"Iron Treads","paradox":true},
{"dex":991,"name":"Eisenbündel","en":"Iron Bundle","paradox":true},
{"dex":992,"name":"Eisenhand","en":"Iron Hands","paradox":true},
{"dex":993,"name":"Eisenhals","en":"Iron Jugulis","paradox":true},
{"dex":994,"name":"Eisenfalter","en":"Iron Moth","paradox":true},
{"dex":995,"name":"Eisendorn","en":"Iron Thorns","paradox":true},
{"dex":996,"name":"Frospino","en":"Frigibax"},
{"dex":997,"name":"Cryospino","en":"Arctibax","evolved":true},
{"dex":998,"name":"Espinodon","en":"Baxcalibur","evolved":true},
{"dex":999,"name":"Gierspenst (Truhenform)","en":"Gimmighoul (Chest Form)"},
{"dex":"999R","name":"Gierspenst (Wanderform)","en":"Gimmighoul (Roaming Form)"},
{"dex":1000,"name":"Monetigo","en":"Gholdengo","evolved":true},
{"dex":1001,"name":"Chongjian","en":"Wo-Chien","legendary":true},
{"dex":1002,"name":"Baojian","en":"Chien-Pao","legendary":true},
{"dex":1003,"name":"Dinglu","en":"Ting-Lu","legendary":true},
{"dex":1004,"name":"Yuyu","en":"Chi-Yu","legendary":true},
{"dex":1005,"name":"Donnersichel","en":"Roaring Moon","paradox":true},
{"dex":1006,"name":"Eisenkrieger","en":"Iron Valiant","paradox":true},
{"dex":1007,"name":"Koraidon","legendary":true},
{"dex":1008,"name":"Miraidon","legendary":true},
{"dex":1009,"name":"Windewoge","en":"Walking Wake","paradox":true},
{"dex":1010,"name":"Eisenblatt","en":"Iron Leaves","paradox":true}
];
