var region = "Wedding";

var gymjson = {
"gyms": [
{"value":"1892 Historisches Gebäude","ex":true,"token":"historisches haus","map":"https://goo.gl/maps/LJthotdr7b72"},
{"value":"Adorant (Betender Jüngling)","map":"https://goo.gl/maps/HGCr96thMfhhn9Sb6"},
{"value":"Alien Painting","map":"https://goo.gl/maps/LjnC6KmVLzJ6XRqH9"},
{"value":"Alte Turmuhr","map":"https://goo.gl/maps/yyRLUHUpNrnR33zt8"},
{"value":"Amtsgericht Wedding","ex":true,"map":"https://goo.gl/maps/q79rW3P5iz82"},
{"value":"Antikriegsdenkmal","map":"https://goo.gl/maps/CBNhqsGi2Bd6r4k99"},
{"value":"Bahnhof Humboldthain","token":"s-bahnhof","map":"https://goo.gl/maps/NoMxjQmX8Yz"},
{"value":"Balance on the Globe","ex":true,"tg":"Balance On The Globe","map":"https://goo.gl/maps/bM2QWrCkDhq"},
{"value":"Beuth Hochschule für Technik","ex":true,"map":"https://goo.gl/maps/mj6fTamuHCL6iUe59"},
{"value":"Birkenmural","ex":true,"map":"https://goo.gl/maps/LUjPLZgELHR2"},
{"value":"BLO 2011","map":"https://goo.gl/maps/BRT63XWQVaojFm5S9"},
{"value":"Brunnen: Tanz auf dem Vulkan","map":"https://goo.gl/maps/DYjujPe8rBoKwqGa6"},
{"value":"Das Überraschende macht Glück","map":"https://goo.gl/maps/iGjycPqrinC5nvhb7"},
{"value":"Erika Hess Eisstadion","map":"https://goo.gl/maps/J9Nur9FFXcsnwYwB6"},
{"value":"Fennbridge Rebuild 1950-1952","map":"https://goo.gl/maps/pnpijLTBVsoWaFUu8"},
{"value":"Forum Seestraße","map":"https://goo.gl/maps/DjMeStbNSZDdqtht6"},
{"value":"Gewachsen auf Beton Mural","ex":true,"token":"u-bahnhof pankstraße","map":"https://goo.gl/maps/8MVUihQXCQ82"},
{"value":"Graffiti Art Lynarstraße","map":"https://goo.gl/maps/1L3BeBCPJVQehLJB7"},
{"value":"Jux und Tollerei","map":"https://goo.gl/maps/vLZcbgbGXrD2"},
{"value":"Kamel","ex":true,"token":"🐫 🐪","map":"https://goo.gl/maps/xCWVtJhqw1r"},
{"value":"Kapernaum-Kirche","map":"https://goo.gl/maps/54UhGkt7WdjJCxXE7"},
{"value":"Kieler Brücke","map":"https://goo.gl/maps/j4Efjkm3TSLLdE2t9"},
{"value":"Kinderfarm ev","ex":true,"map":"https://goo.gl/maps/maG6rK8N9ekyHLmo6"},
{"value":"Kunst am Verteilerkasten","tg":"Kunst Am Verteilerkasten","map":"https://goo.gl/maps/A5m6neb645wATjc96"},
{"value":"Leopold Gmelin 1788-1853","map":"https://goo.gl/maps/xjeoG8mCxb1LQxmt5"},
{"value":"New Nazareth Church","ex":true,"map":"https://goo.gl/maps/LzYmeGovo3Kw48538"},
{"value":"Old Nazareth Church","map":"https://goo.gl/maps/V8bwoWaxodbw3z9R8"},
{"value":"Photo and Flowers","map":"https://goo.gl/maps/nhepDUHwQaWKjzRz9"},
{"value":"Portal zur Kaiser Wilhelm und Augusta Stiftung","tg":"Portal zur Kaiser Wilhelm Und Augusta Stiftung","map":"https://goo.gl/maps/Z132sxwCnHE2"},
{"value":"Schönwalder Straßenbrücke","tg":"Schoenwalder Strassenbruecke","map":"https://goo.gl/maps/n5gAnPhfmWFpCgHWA"},
{"value":"Seller Brücke","ex":true,"map":"https://goo.gl/maps/Sx8LydBB6SHUze9WA"},
{"value":"Skulptur am Robert Koch Institut","map":"https://goo.gl/maps/4gXrcCg37zz2WsBx7"},
{"value":"Springbrunnen am Rathaus","ex":true,"tg":"Springbrunnen Am Rathaus","map":"https://goo.gl/maps/j5WL5s81k2K2"},
{"value":"St. Joseph Kirche","map":"https://goo.gl/maps/Vt8JmUjCpeTMebqF8"},
{"value":"Stolperstein Marie Kairies","map":"https://goo.gl/maps/9SkryjFjoT4MtAdi9"},
{"value":"Stolpersteine Georg und Rudolf Juliusburger","ex":true,"tg":"Stolpersteine Georg Und Rudolf Juliusburger","token":"jüdisches krankenhaus jewish hospital","map":"https://goo.gl/maps/kPsKT4sGpPK2"},
{"value":"Street Art Dancing Penguin","map":"https://goo.gl/maps/b2fZwPJ9N8N2KHit8"},
{"value":"The Fountain 2","map":"https://goo.gl/maps/q1e3ZfKhhWcdfWsr7"},
{"value":"Timezone Seestraße","map":"https://goo.gl/maps/RQA2Wz11JcKQ9wCP7"},
{"value":"Torfstraßensteg","tg":"Torfstrassensteg","map":"https://goo.gl/maps/WrJzXRvP3Ery3HM16"},
{"value":"Tram Seestraße","map":"https://goo.gl/maps/HUcqkH5RFLYSdutE8"},
{"value":"Tram Wc","ex":true,"map":"https://goo.gl/maps/LNVCFPfNkUMvSnoq5"},
{"value":"Trümmersäule","ex":true,"map":"https://goo.gl/maps/yAo3DyY5TojF6q37A"},
{"value":"U-Bahnhof Osloer Straße","ex":true,"tg":"U-Bahnhof Osloer Strasse","map":"https://goo.gl/maps/67rcURgu1Y82"},
{"value":"Verzierte Fassade","map":"https://goo.gl/maps/Ku389HXsb8HNgifw6"},
{"value":"Virchow's Angels","map":"https://goo.gl/maps/bzRgsLVg4ip8LZbc7"},
{"value":"Wappen","map":"https://goo.gl/maps/7EJPSrw1E7XnKZut7"},
{"value":"Wasserturm","map":"https://goo.gl/maps/UGMEedx6KQxeJT6e9"},
{"value":"Wilhelm-Hasenclever-Platz","map":"https://goo.gl/maps/hAG4KaovnjxAd6zZ8"},
{"value":"Wintergarten Reinickendorfer Straße","tg":"Wintergarten Reinickendorferst","map":"https://goo.gl/maps/NcNQ5PDLuMFJxZkN8"}
]};

var boqlink = "https://www.bookofquests.de/#14/1485750.97/6900116.96/0/f=";